import type { Night, ShopItem } from './types'

export const CHARACTERS: Record<string, { name: string; color: string }> = {
  me: { name: '我', color: '#7dd3fc' },
  zhou: { name: '老周', color: '#fbbf24' },
  tang: { name: '小唐', color: '#f9a8d4' },
  mother: { name: '年轻妈妈', color: '#fda4af' },
  father: { name: '年轻爸爸', color: '#a5b4fc' },
  worker: { name: '工地大叔', color: '#fdba74' },
  thin: { name: '瘦高青年', color: '#c4b5fd' },
  mystery: { name: '陌生男人', color: '#a8a29e' },
  aunt: { name: '体检科阿姨', color: '#f0abfc' },
  lei: { name: '小雷 · 信息科', color: '#93c5fd' },
  fan: { name: '老范 · 设备科', color: '#d6d3d1' },
  he: { name: '小何 · 急诊科', color: '#86efac' },
  kai: { name: '阿凯 · 厂家工程师', color: '#67e8f9' },
  director: { name: '科主任', color: '#cbd5e1' },
  wen: { name: '雯雯 · 厂家销售', color: '#fcd34d' },
  bai: { name: '老白 · 配件商', color: '#e7e5e4' },
  qian: { name: '☎️ 医保办 · 钱姐', color: '#a5b4fc' },
  jiang: { name: '📻 后勤处 · 老蒋', color: '#a8a29e' },
  oldman: { name: '流浪老人', color: '#d6d3d1' },
  sys: { name: '', color: '#94a3b8' },
}

export const BADGES: Record<string, { name: string; icon: string; desc: string; hidden?: boolean }> = {
  first_night: { name: '初夜纪念', icon: '🌙', desc: '完成第一个夜班' },
  battery_hunter: { name: '电池猎手', icon: '🔋', desc: '准确识别纽扣电池的双环征' },
  sharp_eye: { name: '火眼金睛', icon: '👁️', desc: '第一章全程零误诊' },
  fixer: { name: '修理工的荣耀', icon: '🔧', desc: '亲手修好一次设备' },
  money_bags: { name: '精打细算', icon: '💰', desc: '第一章结束时存款超过600金币' },
  chapter1: { name: '老伙计的荣耀', icon: '🏅', desc: '通关第一章：X光' },
  night_owl: { name: '夜猫子', icon: '🦉', desc: '连续打卡3天' },
  warm_hands: { name: '温柔的手', icon: '🤲', desc: '安慰了每一位焦虑的病人或家属' },
  detective: { name: '夜班侦探', icon: '🔍', desc: '查清旧片库与「残影」的真相' },
  shopaholic: { name: '小卖部VIP', icon: '🛒', desc: '在小卖部消费3次以上' },
  quiz_master: { name: '学霸技师', icon: '🎓', desc: '晨会考核拿到满分' },
}

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'coffee', icon: '☕', name: '速溶咖啡', price: 30, desc: '行动力 +1，夜班续命水' },
  { id: 'milktea', icon: '🧋', name: '全科室奶茶', price: 200, desc: '请全科夜班同事喝一轮，人心 +2' },
  { id: 'snack', icon: '🍪', name: '零食礼包', price: 40, desc: '送人好物，解锁「分享零食」选项' },
  { id: 'book', icon: '📖', name: '二手《医学影像学》', price: 100, desc: '前任主人的笔记密密麻麻，医术 +2' },
  { id: 'lottery', icon: '🎫', name: '刮刮乐', price: 50, desc: '夜班玄学：偶尔单车变摩托，久刮必亏' },
  { id: 'toolbox', icon: '🔧', name: '工具箱', price: 150, desc: '万用表、绝缘胶带、备用保险丝——修理设备时更安全' },
  { id: 'dosimeter', icon: '📟', name: '个人剂量计', price: 200, desc: '别在领口的辐射监测仪，解锁特殊的查看选项' },
  { id: 'key', icon: '🗝️', name: '黄铜钥匙', price: 120, desc: '老板娘代收的旧货，据说能开旧片库角落里的小铁柜', minNight: 2 },
]

export const NIGHTS: Night[] = [
  // ================= 第 1 夜 =================
  {
    id: 1,
    title: '第 1 夜',
    subtitle: '老伙计',
    start: 'n1_s0',
    steps: {
      n1_s0: { bg: 'bg_control', speaker: 'sys', text: '晚上九点半，澜江市禾川县人民医院影像科。这是你独立值夜班的第一个晚上。', next: 'n1_s1' },
      n1_s1: { speaker: 'tang', sprite: 'char_tang', sfx: 'vox_tang', text: '新同事！我是小唐，今晚的值班护士。别紧张，夜班嘛——要么闲得长蘑菇，要么忙到飞起，没有中间态。', next: 'n1_s2' },
      n1_s2: { speaker: 'tang', sprite: 'char_tang', text: '先打卡！门口那台打卡机，打了卡才算上岗。以后每天来都要打哦，连续打卡有奖励的。', next: 'n1_s3' },
      n1_s3: { speaker: 'sys', text: '【点击打卡机打卡】', sprite: 'char_tang', choices: [{ text: '📮 打卡上岗', next: 'n1_s4', effect: { gold: 50 } }] },
      n1_s4: { speaker: 'sys', text: '「咔哒」——打卡成功。金币 +50。', sfx: 'stamp', next: 'n1_s5' },
      n1_s5: { speaker: 'zhou', sprite: 'char_zhou', sfx: 'vox_zhou', text: '新来的？我是老周，放射科医师。先说清楚：今晚这台X光机比我工龄都大，你温柔点对它，它就温柔点对你。', sprite2: 'char_tang', next: 'n1_s5b' },
      n1_s5b: { speaker: 'zhou', sprite: 'char_zhou', text: '对了，你医工学院来的，先把岗位搞清楚：大医院里「拍片」和「看片」是两个人——技师岗管摆位、调参数、曝光出图；影像医师岗管读片、写诊断、签报告，执照都不一样。咱小医院夜班就你一个，只能身兼两职：片子你拍，初诊你先筛，正式报告第二天我来签。别慌，大事随时打电话喊我。', sprite2: 'char_tang', next: 'n1_s6' },
      n1_s6: { speaker: 'me', text: '（看了眼墙角那台吱呀作响的老X光机）……它真的还能用吗？', sprite: 'char_zhou', next: 'n1_s7' },
      n1_s7: { speaker: 'zhou', sprite: 'char_zhou', text: '瞧不起谁呢。拍骨头、找异物，它比谁都利索。……离十点接诊还有一会儿，你自己先在科里转转，认认门。', next: 'n1_s7b' },
      n1_s7b: { speaker: 'zhou', sprite: 'char_zhou', text: '先跟你交个底：老伙计是台CR——图像存在IP成像板上，拍完得抱着板子去扫描仪里激光读出，一套流程下来黄花菜都凉了。楼上DR机房那台新机拍完秒出图，可那是主任的命根子，晚上上锁，白班专科技师才有权限碰。咱夜班急诊，就配用这老古董。', next: 'n1_s7c' },
      n1_s7c: { speaker: 'me', text: '（都什么年代了还在抱着板子跑……你默默吐槽。）那隔壁介入室那台大机器呢？', sprite: 'char_zhou', next: 'n1_s7d' },
      n1_s7d: { speaker: 'zhou', sprite: 'char_zhou', text: 'C型臂DSA，心内科做冠脉造影的宝贝，实时减影看血管，启动一次的热容量够老伙计跑一个礼拜。那屋子你连门都别挨——真想学，等以后有胆子跟介入科跟台再说。', next: 'n1_hubintro' },
      n1_hubintro: { speaker: 'tang', sprite: 'char_tang', text: '（小唐塞给你一张手绘地图）喏，值班室有泡面，走廊尽头是小卖部，十点开诊前随便逛。每去一个地方要花一点行动力，量力而行哦。', effect: { ap: 3 }, next: 'n1_hub' },

      n1_hub: { speaker: 'sys', text: '【自由行动 · 去哪转转？】（行动力见顶部 ⚡）', choices: [
        { text: '🛒 小卖部逛逛（不耗行动力）', next: '@shop' },
        { text: '📖 翻翻值班室那本旧书（不耗行动力）', next: '@book' },
        { text: '🚶 去走廊转转（⚡-1）', next: 'n1_walk0', effect: { ap: -1, flag: 'n1_walk' }, cond: { ap: 1, notFlag: 'n1_walk' } },
        { text: '🛋️ 去值班室歇脚（⚡-1）', next: 'n1_rest0', effect: { ap: -1, flag: 'n1_rest' }, cond: { ap: 1, notFlag: 'n1_rest' } },
        { text: '🗄️ 看看走廊尽头那扇旧门（⚡-1）', next: 'n1_arc0', effect: { ap: -1, flag: 'n1_arc' }, cond: { ap: 1, notFlag: 'n1_arc' } },
        { text: '🩺 时间差不多了，去检查室开工', next: 'n1_case0' },
      ]},
      n1_walk0: { bg: 'bg_corridor', speaker: 'sys', text: '走廊灯光昏黄。一个戴眼镜的年轻人正踩在梯子上，捣鼓天花板下的无线AP，笔记本悬在半空摇摇欲坠。', next: 'n1_walk1' },
      n1_walk1: { speaker: 'lei', sprite: 'char_lei', sfx: 'vox_lei', text: '欸欸欸——搭把手扶下梯子！谢了……我是信息科小雷，PACS今晚又抽风，影像传不上工作站，我来抢修。', next: 'n1_walk2' },
      n1_walk2: { speaker: 'lei', sprite: 'char_lei', text: '你们科今晚要是图像传不过去，先重启工作站，不行就打我分机。……对了，你是新来的吧？晚上少往三楼旧片库那边去。', next: 'n1_walk3' },
      n1_walk3: { speaker: 'sys', text: '【怎么回应？】', sprite: 'char_lei', choices: [
        { text: '「为什么？那边有什么？」', next: 'n1_walk4a', effect: { flag: 'met_lei' } },
        { text: '「好，我记住了。」（帮他扶梯子到修完）', next: 'n1_walk4b', effect: { heart: 1, gold: 20, flag: 'met_lei' }, tag: 'good', risk: { chance: 0.3, next: 'n1_walk4r', effect: { ap: -1 } } },
      ]},
      n1_walk4a: { speaker: 'lei', sprite: 'char_lei', text: '（压低声音）老楼传说呗——值班的说半夜听见片库里有翻片子的声音，沙沙的，像有人在找东西。我猜是老鼠。……应该是老鼠吧。', next: 'n1_walk5' },
      n1_walk4b: { speaker: 'lei', sprite: 'char_lei', text: '谢啦！下回请你喝奶茶。……哦对，三楼旧片库晚上别去，老楼传说不太平。当听个乐。', next: 'n1_walk5' },
      n1_walk4r: { speaker: 'sys', sprite: 'char_lei', text: '（意外）扶梯子时你踩空了半级，脚踝「咯」地一声。小雷吓坏了，你摆摆手说没事——可走起路来还是有点使不上劲。（行动力-1）', next: 'n1_walk4b' },
      n1_walk5: { speaker: 'sys', text: '小雷抱着笔记本匆匆走了。PACS恢复正常。（回到科室）', next: 'n1_hub' },
      n1_rest0: { bg: 'bg_breakroom', speaker: 'sys', text: '值班室不大：一张旧沙发、一台微波炉、墙上贴着排班表。桌角放着一本翻烂的《医学影像学》，扉页写着「夜班保命，闲时翻翻」。', next: 'n1_rest1' },
      n1_rest1: { speaker: 'sys', text: '【做点什么呢？】', choices: [
        { text: '眯十分钟，养养神（恢复一点行动力）', next: 'n1_rest2a', effect: { ap: 1 } },
        { text: '翻翻那本旧书', next: 'n1_rest2b', effect: { skill: 1 }, tag: 'good' },
      ]},
      n1_rest2a: { speaker: 'sys', text: '你蜷在沙发上打了个盹。梦里全是嗡嗡的机器声。（回到科室）', next: 'n1_hub' },
      n1_rest2b: { speaker: 'sys', text: '书页间夹着一张便签：「拍片先问病史，曝光先想剂量。」字迹已经褪色。（回到科室）', next: 'n1_hub' },
      n1_arc0: { bg: 'bg_corridor', speaker: 'sys', text: '走廊尽头有一扇斑驳的铁门，门牌字迹模糊：「片库」。门把手上挂着一把老式挂锁，锁孔里插着半截断钥匙。', next: 'n1_arc1' },
      n1_arc1: { speaker: 'me', text: '（凑近门缝）里面黑漆漆的，隐约有股旧纸张和显影液的味道。……这就是小雷说的旧片库？', next: 'n1_arc2' },
      n1_arc2: { speaker: 'sys', text: '你正贴着门缝看，身后「啪嗒」一声——声控灯灭了。你决定还是先回科室。（获得线索：旧片库）', effect: { flag: 'archive_seen' }, next: 'n1_hub' },

      n1_case0: { bg: 'bg_control', speaker: 'sys', text: '晚上十点，分诊铃响了。', next: 'n1_s8' },
      n1_s8: { bg: 'bg_xrayroom', speaker: 'mother', sprite: 'pat_child', sfx: 'vox_mom', sfx2: 'cry_child', text: '医生！医生！我儿子、我儿子好像吞了个东西！刚才玩玩具的时候——他说肚子里有东西！', next: 'n1_s9' },
      n1_s9: { speaker: 'me', text: '孩子脸色还好，能正常呼吸，但一直捂着肚子哭。吞食异物……得先弄清楚吞的是什么、卡在什么位置。', sprite: 'pat_child', next: 'n1_s10' },
      n1_s10: { speaker: 'sys', text: '【怎么办？】', sprite: 'pat_child', choices: [
        { text: '先详细问妈妈：什么时候吞的、可能是什么', next: 'n1_s11a', effect: { skill: 1, heart: 1 }, tag: 'good' },
        { text: '别问了，直接拍腹部X光片', next: 'n1_s11b', tag: 'neutral' },
        { text: '建议马上做CT，看得更清楚', next: 'n1_s11c', effect: { skill: -1 }, tag: 'bad' },
      ]},
      n1_s11a: { speaker: 'mother', sprite: 'pat_child', text: '就、就半小时前！我在厨房做饭，回头就看见他把遥控器拆了……电池！遥控器里少了一颗纽扣电池！', next: 'n1_s12' },
      n1_s11b: { speaker: 'zhou', sprite: 'char_zhou', text: '慢着。拍片前问清楚病史是基本功——吞的什么、什么时候吞的，直接决定你要找什么、多着急。记住，问病史不花一分钱，有时比机器更管用。', next: 'n1_s12' },
      n1_s11c: { speaker: 'zhou', sprite: 'char_zhou', text: 'CT？咱科那台CT开春就趴窝了，球管烧了，厂家说配件停产，修一下顶半台新机——院里正琢磨直接换新的呢。再说了，孩子吞异物，一张腹平片又快又清楚，辐射剂量只有CT的零头。杀鸡不用牛刀，懂？', next: 'n1_s12' },
      n1_s12: { speaker: 'me', text: '半小时前吞的，可能是纽扣电池。拍一张腹部立位平片，马上就能见分晓。', next: 'n1_pos' },
      n1_pos: { speaker: 'sys', text: '小唐帮着把孩子扶上检查床摆好位置。你走进控制室，看着操作面板上的管电压（kV）和毫安秒（mAs）旋钮——', sprite: 'pat_child', next: 'n1_mas0' },
      n1_mas0: { speaker: 'zhou', sprite: 'char_zhou', text: '先别急着拧。考你一下：面板上这个毫安秒（mAs），跟管电流（mA）是什么关系？', next: 'n1_mas1' },
      n1_mas1: { speaker: 'sys', text: '【怎么回答？】', sprite: 'char_zhou', choices: [
        { text: '「mAs = 管电流 × 曝光时间，是这一次曝光的总输出量。」', next: 'n1_mas2a', effect: { skill: 1 }, tag: 'good' },
        { text: '「mAs 是 mA 的平方？」', next: 'n1_mas2b', tag: 'neutral' },
        { text: '「呃……同一个东西的两种写法？」', next: 'n1_mas2b', tag: 'neutral' },
      ]},
      n1_mas2a: { speaker: 'zhou', sprite: 'char_zhou', text: '对。管电流就是单位时间从灯丝奔向靶面的电子流，像水龙头的「流量」；乘上曝光时间，mAs 就是这次曝光放出的「总水量」——X光子的总数。你们工科生看着亲：1 mAs = 1 毫库仑，是电荷量的账。管电压管「每个光子有多硬」，毫安秒管「一共放出多少个」，别搞混。', next: 'n1_kv' },
      n1_mas2b: { speaker: 'zhou', sprite: 'char_zhou', text: '不对。管电流（mA）是单位时间从灯丝奔向靶面的电子流，像水龙头的「流量」；mAs 是流量乘上曝光时间，是这次曝光放出的「总水量」——X光子的总数。你们工科生看着亲：1 mAs = 1 毫库仑，是电荷量的账。管电压管「每个光子有多硬」，毫安秒管「一共放出多少个」。记住了，下回还考你。', next: 'n1_kv' },
      n1_kv: { speaker: 'sys', text: '【曝光参数怎么选？】（拿不准可以翻教材或课件）', sprite: 'pat_child', choices: [
        { text: '孩子小，能省则省：kV 和 mAs 都压到最低档', next: 'n1_kv_low', effect: { skill: -1, flag: 'n1_wrong' }, tag: 'bad' },
        { text: '按孩子体重选标准档位', next: 'n1_kv_ok', effect: { skill: 1 }, tag: 'good' },
        { text: '怕看不清，kV 和 mAs 都拉满', next: 'n1_kv_high', effect: { skill: -1, flag: 'n1_wrong' }, tag: 'bad' },
      ]},
      n1_kv_low: { speaker: 'zhou', sprite: 'char_zhou', text: '（看着屏幕上发白发淡的图像直摇头）管电压决定X光子的穿透力，kV太低，光子全被孩子的肚子留下了，探测器没收到几个——图像自然淡。重拍一张吧，等于吃了双倍剂量，这就是贪小便宜的代价。', next: 'n1_shield' },
      n1_kv_ok: { speaker: 'sys', text: '参数合适。老周在旁边瞥了一眼，没说话——在他这儿，没挨骂就是表扬。', next: 'n1_shield' },
      n1_kv_high: { speaker: 'zhou', sprite: 'char_zhou', text: '（一把按住你的手）拉满？图像黑得跟锅底一样，孩子的剂量还翻了好几倍。kV和mAs是「够用就好」，不是「越高越好」——每一毫安秒都是病人实打实吃进去的辐射。调回标准档。', next: 'n1_shield' },
      n1_shield: { speaker: 'sys', text: '曝光就绪。你站在哪儿按曝光按钮？', choices: [
        { text: '控制室的铅玻璃后面', next: 'n1_shield_ok', effect: { skill: 1 }, tag: 'good' },
        { text: '凑在检查室门口，顺便看着孩子', next: 'n1_shield_bad', effect: { skill: -1 }, tag: 'bad' },
        { text: '📟 先别上剂量计，再站回铅玻璃后实测一下', next: 'n1_shield_dose', cond: { item: 'dosimeter' }, effect: { skill: 1, flag: 'dose_curious' }, tag: 'good' },
      ]},
      n1_shield_ok: { speaker: 'me', text: '铅玻璃后面。散射线的方向是四面八方的——隔着铅玻璃、再拉开距离，到我身上的剂量就只剩零头了。夜班要值几十年，防护是给自己上的保险。', next: 'n1_s13' },
      n1_shield_bad: { speaker: 'zhou', sprite: 'char_zhou', text: '（一把把你拽回控制室）站门口吃散射线？病人体内的X光子撞出来是会拐弯的，专往门口钻！铅玻璃、铅衣、距离——记住这三样，是你后半辈子的本钱。', next: 'n1_s13' },
      n1_shield_dose: { speaker: 'sys', text: '你把剂量计别在领口。曝光瞬间，铅玻璃后的读数只微微跳了一下——几乎全是本底。屏蔽加距离，确实把散射线挡干净了。（这条经验，比教科书上的公式记得牢。）', next: 'n1_s13' },
      n1_s13: { speaker: 'sys', text: '「嘀——咔！」曝光完成。你抽出IP成像板——潜影已经藏在板子里了，但肉眼还什么都看不见。', sfx: 'xray', next: 'n1_s13r' },
      n1_s13r: { speaker: 'sys', text: '你快步把IP板送到隔壁，推进扫描仪，按下读取键。', readout: 'xray_battery', next: 'n1_s15' },
      n1_s15: { speaker: 'me', text: '图像出来了。腹部正中有一个圆圆的金属高密度影……等等，仔细看它的边缘。', image: 'xray_battery', next: 'n1_s16' },
      n1_s16: { speaker: 'sys', text: '【片子上这个圆形高密度影，边缘有一圈「双环」样的轮廓。这是——】', image: 'xray_battery', choices: [
        { text: '一枚硬币', next: 'n1_s17a', effect: { skill: -1, flag: 'n1_wrong' }, tag: 'bad' },
        { text: '一颗纽扣电池', next: 'n1_s17b', effect: { skill: 2, badge: 'battery_hunter' }, tag: 'good' },
        { text: '一个围棋子', next: 'n1_s17c', effect: { skill: -1, flag: 'n1_wrong' }, tag: 'bad' },
      ]},
      n1_s17a: { speaker: 'zhou', sprite: 'char_zhou', image: 'xray_battery', text: '再仔细看看。硬币边缘是均匀的一圈，这个影子是「双环」——外圈套内圈，像个小甜甜圈。这是纽扣电池的招牌长相，因为它正负极叠在一起。', next: 'n1_s18' },
      n1_s17b: { speaker: 'zhou', sprite: 'char_zhou', image: 'xray_battery', text: '漂亮！一眼就抓住双环征了。记住：硬币边缘是均匀一圈，纽扣电池是双环——这俩在片子上长得像，但凶险程度天差地别。', sfx: 'badge', next: 'n1_s18' },
      n1_s17c: { speaker: 'zhou', sprite: 'char_zhou', image: 'xray_battery', text: '围棋子是塑料的，X光下根本看不见影。你看这边缘的「双环」——外圈套内圈。这是纽扣电池，记住这个长相，关键时刻能救命。', next: 'n1_s18' },
      n1_s18: { speaker: 'zhou', sprite: 'char_zhou', text: '纽扣电池卡在消化道，两小时就能烧穿黏膜。别愣着，马上通知消化内镜中心，今晚就得取出来！', next: 'n1_s19' },
      n1_s19: { speaker: 'mother', sprite: 'pat_child', text: '谢谢你们……谢谢！那、那要是硬币的话，是不是就不用手术了？', next: 'n1_kind' },
      n1_kind: { speaker: 'sys', text: '【怎么跟她说？】', sprite: 'pat_child', choices: [
        { text: '耐心解释：硬币大多能自己排出来，但电池会漏液烧蚀，等不得', next: 'n1_s20', effect: { heart: 1, flag: 'n1_kind' }, tag: 'good' },
        { text: '「肯定没事，放心吧，大部分都能自己排出来！」（先安抚住她）', next: 'n1_over0', tag: 'neutral' },
        { text: '「听医生安排就行了。」', next: 'n1_s20', tag: 'neutral' },
      ]},
      n1_over0: { speaker: 'tang', sprite: 'char_tang', text: '（小唐拉了拉你的袖子，压低声音）话不能这么说——现在还没确定是不是电池，万一真是，每一分钟都在烧黏膜。安慰家属是好心，但结论不能抢在检查前面，更不能替内镜中心打包票。', next: 'n1_over1' },
      n1_over1: { speaker: 'mother', sprite: 'pat_child', text: '「到底是有事还是没事啊？！」妈妈反而更慌了。你好一阵解释，才把话说圆。（技术-1：安慰要有依据）', effect: { skill: -1 }, next: 'n1_s20' },
      n1_s20: { speaker: 'sys', text: '孩子被紧急送去内镜中心。凌晨一点，电池顺利取出，母子平安。', next: 'n1_s21' },
      n1_s21: { speaker: 'tang', sprite: 'char_tang', text: '第一夜就立了一功！……欸，你有没有觉得，刚才看片的时候你眼睛会发光？', next: 'n1_s22' },
      n1_s22: { speaker: 'sys', text: '【今夜结算】诊疗收入 +200 金币', effect: { gold: 200, badge: 'first_night' }, stamp: true, next: 'n1_end' },
      n1_end: { end: true },
    },
  },
  // ================= 第 2 夜 =================
  {
    id: 2,
    title: '第 2 夜',
    subtitle: '机器的脾气',
    start: 'n2_s0',
    steps: {
      n2_s0: { bg: 'bg_control', speaker: 'sys', text: '第二夜。你推开科室大门，打卡机的灯还亮着。', next: 'n2_s1' },
      n2_s1: { speaker: 'sys', text: '【今日打卡】', choices: [{ text: '📮 打卡上岗', next: 'n2_s2', effect: { gold: 50 } }] },
      n2_s2: { speaker: 'sys', text: '「咔哒」——打卡成功。金币 +50。', sfx: 'stamp', next: 'n2_s3' },
      n2_s3: { speaker: 'tang', sprite: 'char_tang', text: '今晚听说了吗，工地那边脚手架塌了，急诊收了好几个。老周让你先把X光室准备好——离开诊还有一会儿，你也可以先在楼里转转。', effect: { ap: 3 }, next: 'n2_hub' },

      n2_hub: { speaker: 'sys', text: '【自由行动 · 去哪转转？】（行动力见顶部 ⚡）', choices: [
        { text: '🛒 小卖部逛逛（不耗行动力）', next: '@shop' },
        { text: '📖 翻翻值班室那本旧书（不耗行动力）', next: '@book' },
        { text: '🔧 去设备科串串门（⚡-1）', next: 'n2_fan0', effect: { ap: -1, flag: 'n2_fan' }, cond: { ap: 1, notFlag: 'n2_fan' } },
        { text: '🚶 去走廊转转（⚡-1）', next: 'n2_walk0', effect: { ap: -1, flag: 'n2_walk' }, cond: { ap: 1, notFlag: 'n2_walk' } },
        { text: '🛋️ 去值班室歇脚（⚡-1）', next: 'n2_rest0', effect: { ap: -1, flag: 'n2_rest' }, cond: { ap: 1, notFlag: 'n2_rest' } },
        { text: '🩺 去检查室开工', next: 'n2_case0' },
      ]},
      n2_fan0: { bg: 'bg_corridor', speaker: 'sys', text: '设备科办公室堆满了零件和报修单。一个头发花白的师傅正蹲在地上，清点刚到货的几只纸箱，嘴里念念有词地对数。', next: 'n2_fan1' },
      n2_fan1: { speaker: 'fan', sprite: 'char_fan', sfx: 'vox_fan', text: '哟，影像科新来的？我姓范，设备科的。全院影像设备的吃喝拉撒都归我采买——这几箱是你们的：超声科的耦合剂、两摞新的铅围裙铅眼镜、还有干式激光打印胶片。', next: 'n2_fan2' },
      n2_fan2: { speaker: 'fan', sprite: 'char_fan', text: '顺嘴说一句：你们夜班那台CR，我上周去瞧过，扫描仪里那根擦除灯管快到寿命了，新灯管还在采购流程里。拍完片，图像以「潜影」存在IP板里，激光读出后得用强光把残影擦除干净，板子才能再用——这几天灯管劲头不足，你们读完记得多擦一遍再装回去。', next: 'n2_fan3' },
      n2_fan3: { speaker: 'sys', text: '【帮老范搭把手？】', sprite: 'char_fan', choices: [
        { text: '帮他把这几箱耗材搬进库房（⚡-1）', next: 'n2_fan4a', effect: { gold: 40, heart: 1, flag: 'fan_friend', ap: -1 }, cond: { ap: 1 }, tag: 'good', risk: { chance: 0.3, next: 'n2_fan4r', effect: { gold: -30 } } },
        { text: '好奇追问：「那擦不干净会怎么样？」', next: 'n2_fan4b', effect: { skill: 1, flag: 'fan_ghost_hint' }, tag: 'good' },
      ]},
      n2_fan4a: { speaker: 'fan', sprite: 'char_fan', text: '好小伙！……对了，旧片库的挂锁钥匙在我抽屉里锁着，那破屋子二十年没人进了，你可别打它主意。（他顿了顿，又补了一句）真有事来找我拿，别自己撬。', effect: { flag: 'fan_key_hint' }, next: 'n2_fan5' },
      n2_fan4b: { speaker: 'fan', sprite: 'char_fan', text: '擦不干净？那上一位病人的影子就会留在板子上，下一位拍出来就是个「叠影」——跟闹鬼似的。这几天灯管老化，尤其容易擦不干净，你们收尾的时候多留个心眼。……问这么细干嘛？', effect: { flag: 'fan_key_hint' }, next: 'n2_fan5' },
      n2_fan5: { speaker: 'sys', text: '老范继续埋头对数。你回了科室。（设备科的路，你摸熟了）', next: 'n2_hub' },
      n2_fan4r: { speaker: 'sys', sprite: 'char_fan', text: '（意外）最上面那箱耦合剂没码稳，「啪」地摔在地上，碎了两瓶。你坚持照价赔偿，老范拗不过，按进货价收了你30金币，嘴里念叨：「心意领了，下回码箱子先大后小。」（金币-30）', next: 'n2_fan4a' },
      n2_walk0: { bg: 'bg_corridor', speaker: 'sys', text: '走廊里突然传来轮子声——一张平车呼啸而过，上面躺着个呻吟的病人，推车的女医生边跑边喊：「让让！骨科急诊！」', next: 'n2_walk1' },
      n2_walk1: { speaker: 'he', sprite: 'char_he', sfx: 'vox_he', text: '啊不好意思！——欸，你是影像科的？太好了，我是急诊小何。今晚工地事故，估计一会儿还得麻烦你们科好几次！', next: 'n2_walk2' },
      n2_walk2: { speaker: 'sys', text: '【帮她推一段？】', sprite: 'char_he', choices: [
        { text: '搭把手，帮她把平车推到电梯口（⚡-1）', next: 'n2_walk3a', effect: { gold: 30, heart: 1, flag: 'met_he', ap: -1 }, cond: { ap: 1 }, tag: 'good', risk: { chance: 0.3, next: 'n2_walk3r', effect: { heart: -1 } } },
        { text: '点点头让开路（你们都会有麻烦对方的时候）', next: 'n2_walk3b', effect: { flag: 'met_he' } },
      ]},
      n2_walk3a: { speaker: 'he', sprite: 'char_he', text: '谢啦！回头急诊有活儿我罩着你——开玩笑的，最好谁也别罩着谁，大家平平安安。', next: 'n2_walk4' },
      n2_walk3r: { speaker: 'sys', sprite: 'char_he', text: '（意外）拐弯时平车猛地颠了一下，车上的病人「哎哟」一声，家属立刻沉下脸：「会不会推车啊！」小何赶忙替你赔了不是。（人心-1）', next: 'n2_walk3a' },
      n2_walk3b: { speaker: 'sys', text: '平车消失在电梯口。急诊的人，连影子都是跑的。（回到科室）', next: 'n2_hub' },
      n2_walk4: { speaker: 'sys', text: '（回到科室）', next: 'n2_hub' },
      n2_rest0: { bg: 'bg_breakroom', speaker: 'sys', text: '值班室里，小唐正跟一台不出水的咖啡机较劲。', next: 'n2_rest1' },
      n2_rest1: { speaker: 'tang', sprite: 'char_tang', text: '这破机器又罢工了……夜班没有咖啡，跟船没有桨有什么区别！', next: 'n2_rest2' },
      n2_rest2: { speaker: 'sys', text: '【做点什么？】', sprite: 'char_tang', choices: [
        { text: '帮她看看咖啡机（说不定只是插头松了）', next: 'n2_rest3a', effect: { heart: 1 }, tag: 'good', risk: { chance: 0.3, next: 'n2_rest3r', effect: { wealth: -1 } } },
        { text: '🍪 把零食礼包拆开和她分着吃', next: 'n2_rest3b', cond: { item: 'snack' }, effect: { heart: 2, loseItem: 'snack' }, tag: 'good' },
        { text: '陪她一起骂两句咖啡机', next: 'n2_rest3c' },
      ]},
      n2_rest3a: { speaker: 'sys', text: '你把插头拔下来重插、拍了拍水箱——咖啡机嗡嗡地复活了。小唐给你接了第一杯：「救命恩人！」（回到科室）', next: 'n2_hub' },
      n2_rest3r: { speaker: 'sys', text: '（意外）你拆开咖啡机后盖，「啪」地冒了朵小火花——机器彻底没声了。小唐哭笑不得：「它本来还能出半杯的……」你默默把后盖装了回去，护士站的公物清单上多了一笔报损。（家业-1）（回到科室）', next: 'n2_hub' },
      n2_rest3b: { speaker: 'tang', sprite: 'char_tang', text: '哇——你居然带了这个！夜班零食是硬通货你懂不懂！（她嘴上说着，把最大的一块让给了你。）（回到科室）', next: 'n2_hub' },
      n2_rest3c: { speaker: 'sys', text: '你们对着咖啡机输出了三分钟。它没有悔改的意思。（回到科室）', next: 'n2_hub' },

      n2_case0: { bg: 'bg_control', speaker: 'sys', text: '晚上十点，开诊。第一个病人几乎是被人架进来的。', next: 'n2_s4' },
      n2_s4: { bg: 'bg_xrayroom', speaker: 'worker', sprite: 'pat_worker', sfx: 'vox_worker', text: '哎哟……医生轻点轻点。就摔了一跤，胳膊不敢动了。兄弟们都说了没事，我寻思歇两天就好，工头非让我来……', next: 'n2_s5' },
      n2_s5: { speaker: 'me', text: '大叔右前臂肿胀明显，不敢活动。摔伤后局部肿痛畸形，首先要排除骨折。', sprite: 'pat_worker', next: 'n2_s6' },
      n2_s6: { speaker: 'sys', text: '【怎么拍？】', sprite: 'pat_worker', choices: [
        { text: '只拍一张正位片，省事省剂量', next: 'n2_s7a', effect: { skill: -1, flag: 'n2_wrong' }, tag: 'bad' },
        { text: '拍前臂正位+侧位两张', next: 'n2_s7b', effect: { skill: 2 }, tag: 'good' },
        { text: '全身都拍一遍，稳妥', next: 'n2_s7c', effect: { skill: -1, gold: -30, flag: 'n2_wrong' }, tag: 'bad' },
      ]},
      n2_s7a: { speaker: 'zhou', sprite: 'char_zhou', text: '只拍正位？X光是把立体的人压成平面的影子——前后方向的重叠全拍没了。骨折有没有移位、往哪边移，正侧位对着看才知道。这是规矩，别偷懒。', next: 'n2_s8' },
      n2_s7b: { speaker: 'me', text: '正位看左右，侧位看前后——X光片是把立体压成平面，一个体位会丢掉一个维度的信息。两张配合才能判断骨折有没有移位。', next: 'n2_s8' },
      n2_s7c: { speaker: 'zhou', sprite: 'char_zhou', text: '全身拍一遍？大叔是摔了胳膊不是散了架。X光片是有辐射的，查哪拍哪，不多拍一张——这叫正当化原则，也是对病人负责。', next: 'n2_s8' },
      n2_s8: { speaker: 'sys', text: '「嘀——咔！」「嘀——咔！」两张曝光完成。你抽出两块IP板，潜影都好好地藏在板子里。', sfx: 'xray', next: 'n2_s8r' },
      n2_s8r: { speaker: 'sys', text: '两块IP板先后送进隔壁的扫描仪，先读正位。', readout: 'xray_fracture', next: 'n2_s9' },
      n2_s9: { speaker: 'me', text: '正位片上桡骨中段一道清晰的透亮线，侧位片显示断端轻度移位——桡骨骨折，没跑了。', image: 'xray_fracture', next: 'n2_qian0' },
      n2_qian0: { speaker: 'sys', text: '这时，科室电话响了。', image: 'xray_fracture', sfx: 'ring', phone: 'char_qian', next: 'n2_qian1' },
      n2_qian1: { speaker: 'qian', phone: 'char_qian', sfx: 'vox_qian', text: '影像科吗？我医保办小钱。今晚那个工地摔伤的，是外伤，医保这边要排除第三方责任才能直接结算——得留一份详细的受伤经过说明，你们拍片的时候顺带问清楚、写下来，不然大叔报不了销。', next: 'n2_qian2' },
      n2_qian2: { speaker: 'sys', text: '【怎么处理？】', image: 'xray_fracture', phone: 'char_qian', choices: [
        { text: '详细问清受伤时间地点经过，帮大叔把说明写好', next: 'n2_qian3a', effect: { heart: 1, flag: 'qian_helped' }, tag: 'good' },
        { text: '让他明天自己去医保办补手续', next: 'n2_qian3b', tag: 'neutral' },
      ]},
      n2_qian3a: { speaker: 'worker', sprite: 'pat_worker', text: '大夫，你真是个好人呐……我们工地上出来的，最怕这些表格了。', next: 'n2_s10' },
      n2_qian3b: { speaker: 'qian', phone: 'char_qian', text: '……也行吧，就是大叔明天还得再跑一趟。（电话挂了，你听出钱姐语气里的无奈。）', next: 'n2_s10' },
      n2_s10: { speaker: 'worker', sprite: 'pat_worker', text: '真断了啊？！得亏工头逼我来……那啥，医生，我这手还能搬砖不？', next: 'n2_s11' },
      n2_s11: { speaker: 'sys', text: '【安慰一下大叔？】', sprite: 'pat_worker', choices: [
        { text: '「复位固定好，三个月后照样搬砖。先去骨科吧。」', next: 'n2_s12k', effect: { heart: 1, flag: 'n2_kind' }, tag: 'good' },
        { text: '「先治着，看恢复情况。」（递转诊单）', next: 'n2_s12', tag: 'neutral' },
      ]},
      n2_s12k: { speaker: 'zhou', sprite: 'char_zhou', text: '（老周从旁边走过，声音不大，正好只让你听见）安慰病人是好心，但「三个月照样搬砖」这种话，让骨科医生去说。恢复得好，重活可以慢慢捡回来；话说满了，万一恢复得慢，病人心里的落差更大。好心，也要有分寸。', next: 'n2_s12' },
      n2_s12: { speaker: 'sys', text: '大叔千恩万谢地去了骨科。你刚想喝口水，小唐拎着两份盒饭推门进来。', next: 'n2_gossip0' },
      n2_gossip0: { speaker: 'tang', sprite: 'char_tang', text: '加个餐！跟你说，今晚急诊可热闹了——小何为了一袋O型血跟护士长吵起来了，吵到群公告都出来了：「抢救用血先斩后奏，谁拦谁签字」。', next: 'n2_gossip1' },
      n2_gossip1: { speaker: 'tang', text: '还有啊，这两天总有个背皮包的男人在门诊楼晃悠，见人就递名片，保卫科都盯上他了。听说是倒腾二手设备的，专挑老机器多的科室下手。', next: 'n2_gossip2' },
      n2_gossip2: { speaker: 'tang', text: '设备科老范最近也烦——厂家的人隔三差五请他吃饭，他回回黑着脸回来，嘟囔现在的机器花里胡哨，修都没法修。', next: 'n2_gossip3' },
      n2_gossip3: { speaker: 'tang', text: '对了，楼上DR机房那帮白班的，今天又锁门早退，单子上写着「急」也没人管。行了不八卦了——欸，走廊是不是有人咳嗽？', next: 'n2_s13' },
      n2_s13: { speaker: 'mystery', sprite: 'pat_mystery', sfx: 'vox_mystery', text: '医生，麻烦您……我这阵子总是不得劲，说不上哪儿，就是……浑身不对劲。', next: 'n2_s14' },
      n2_s14: { speaker: 'me', text: '一个普普通通的中年男人，查体没发现明显异常。先拍张胸片看看吧。', sprite: 'pat_mystery', next: 'n2_s15' },
      n2_s15: { speaker: 'sys', text: '「嘀——咔！」曝光完成。', sfx: 'xray', next: 'n2_s15r' },
      n2_s15r: { speaker: 'sys', text: '你把IP板送进隔壁扫描仪。读取完成——胸片：心肺膈未见明显异常，一切正常。', readout: 'xray_normal', image: 'xray_normal', next: 'n2_s16' },
      n2_s16: { speaker: 'mystery', sprite: 'pat_mystery', text: '……正常啊。可我真的很不舒服。（他顿了顿，忽然问）医生，咱们医院……还存着很老很老的片子吗？二十年前的那种。', next: 'n2_s16b' },
      n2_s16b: { speaker: 'sys', text: '【怎么回答？】', sprite: 'pat_mystery', choices: [
        { text: '「老片库是有一间，您找谁的片子？」（追问）', next: 'n2_s16c', effect: { flag: 'mystery_asked' }, tag: 'good' },
        { text: '「不清楚，您早点回去休息吧。」', next: 'n2_s17', tag: 'neutral' },
      ]},
      n2_s16c: { speaker: 'mystery', sprite: 'pat_mystery', text: '（他的眼神闪了一下，随即摇头）没什么，随口一问。谢谢医生。（他抱起片袋，走得比来时快了些——你注意到他登记时留的名字，笔迹潦草得像故意写乱的。）', effect: { flag: 'mystery_name' }, next: 'n2_s17' },
      n2_s17: { speaker: 'me', text: '（他把片袋抱在怀里，慢慢走进夜色里。不知道为什么，你觉得这不是最后一次见他。）', next: 'n2_s18' },
      n2_s18: { speaker: 'sys', text: '凌晨三点，你正准备给下一位病人拍片——老X光机突然「啪」地一声闷响，面板全黑了！', next: 'n2_s19' },
      n2_s19: { speaker: 'tang', sprite: 'char_tang', text: '完了完了，后面还有病人排队！厂家工程师上门要300金币，而且得等天亮……要不，你自己试试？', next: 'n2_s20' },
      n2_s20: { speaker: 'sys', text: '【怎么办？】', sprite: 'char_tang', choices: [
        { text: '🔧 用自备工具箱检修（安全又专业）', next: 'n2_fix_tool', cond: { item: 'toolbox' }, tag: 'good' },
        { text: '🔧 徒手试试（免费，但可能修不好）', next: 'n2_fix_self', tag: 'neutral' },
        { text: '📞 叫厂家工程师（-300金币，稳妥）', next: 'n2_fix_pro', effect: { gold: -300 }, cond: { gold: 300 }, tag: 'neutral' },
      ]},
      n2_fix_tool: { speaker: 'me', text: '有工具箱就好办了。X光机不出射线，最常见的死法是球管那一路：灯丝烧电子、高压把电子加速撞到钨靶上，才有X光——灯丝就是机器里的灯泡，先测它的通断。', next: 'n2_fix_tool2' },
      n2_fix_tool2: { speaker: 'sys', text: '万用表一搭：灯丝回路断路。拆开侧板，一股焦味——灯丝保险丝烧了。换上备用的，重新上电……', next: 'n2_fix_tool3' },
      n2_fix_tool3: { speaker: 'sys', text: '面板「嗡」地亮了！小唐欢呼：「我们科室也有自己的工程师了！」', choices: [{ text: '漂亮的活儿！', next: 'n2_s21', effect: { wealth: 2, skill: 1, badge: 'fixer' } }] },
      n2_fix_self: { speaker: 'me', text: '老周教过：这机器的毛病十有八九出在球管上。X光是球管里的灯丝烧到上千度放出电子、电子被高压加速轰击靶面产生的——灯丝跟灯泡一样，是有寿命的。先查灯丝回路。', next: 'n2_fix_roll' },
      n2_fix_roll: { speaker: 'sys', text: '你拆开侧板，闻到一股焦味。灯丝保险丝烧断了——换上备用保险丝，重新上电……', next: 'n2_fix_result' },
      n2_fix_result: { speaker: 'sys', text: '面板「嗡」地亮了起来！修好了！（手上划了道口子，要是有一套称手的工具就好了）', choices: [{ text: '太好了！', next: 'n2_s21', effect: { wealth: 2, badge: 'fixer' } }] },
      n2_fix_pro: { speaker: 'kai', sprite: 'char_kai', sfx: 'vox_kai', text: '天亮时分，厂家工程师阿凯赶到，换了一根球管灯丝。他边修边念叨：「灯丝就是机器里的灯泡，几千度的活儿，到寿就得换。下次过热报警别硬撑——电子撞靶，99%变成热，只有1%变成X光，阳极是拿命在扛。」', next: 'n2_fix_pro2' },
      n2_fix_pro2: { speaker: 'me', text: '（99%变热、1%变X光……难怪这老机器摸起来永远是烫的。你默默记下了这句话。）', sprite: 'char_kai', effect: { skill: 1 }, next: 'n2_s21' },
      n2_s21: { speaker: 'zhou', sprite: 'char_zhou', text: '处理得不错。记住喽，机器跟人一样，你对它上心，它关键时刻才不给你掉链子。', next: 'n2_s22' },
      n2_s22: { speaker: 'sys', text: '【今夜结算】诊疗收入 +250 金币', effect: { gold: 250 }, stamp: true, next: 'n2_end' },
      n2_end: { end: true },
    },
  },
  // ================= 第 3 夜 =================
  {
    id: 3,
    title: '第 3 夜',
    subtitle: '看不见的气',
    start: 'n3_s0',
    steps: {
      n3_s0: { bg: 'bg_control', speaker: 'sys', text: '第三夜。打卡机的灯在夜里格外亮。', next: 'n3_s1' },
      n3_s1: { speaker: 'sys', text: '【今日打卡】', choices: [{ text: '📮 打卡上岗', next: 'n3_s2', effect: { gold: 50 } }] },
      n3_s2: { speaker: 'sys', text: '「咔哒」——打卡成功。金币 +50。', sfx: 'stamp', next: 'n3_s3' },
      n3_s3: { speaker: 'tang', sprite: 'char_tang', text: '今晚好安静啊……（她赶紧捂住嘴）我不说了，一说就灵。离开诊还有一会儿，老规矩，你随意。', effect: { ap: 3 }, next: 'n3_hub' },

      n3_hub: { speaker: 'sys', text: '【自由行动 · 去哪转转？】（行动力见顶部 ⚡）', choices: [
        { text: '🛒 小卖部逛逛（不耗行动力）', next: '@shop' },
        { text: '📖 翻翻值班室那本旧书（不耗行动力）', next: '@book' },
        { text: '🏃 去急诊科看看小何（⚡-1）', next: 'n3_er0', effect: { ap: -1, flag: 'n3_er' }, cond: { ap: 1, notFlag: 'n3_er' } },
        { text: '🗄️ 走廊尽头的旧片库，今晚好像没锁（⚡-1）', next: 'n3_arc0', effect: { ap: -1, flag: 'n3_arc' }, cond: { ap: 1, notFlag: 'n3_arc' } },
        { text: '🛋️ 去值班室歇脚（⚡-1）', next: 'n3_rest0', effect: { ap: -1, flag: 'n3_rest' }, cond: { ap: 1, notFlag: 'n3_rest' } },
        { text: '🩺 去检查室开工', next: 'n3_case0' },
      ]},
      n3_er0: { bg: 'bg_corridor', speaker: 'sys', text: '急诊科灯火通明。小何正在清点抢救车，抬头看见你。', next: 'n3_er1' },
      n3_er1: { speaker: 'he', sprite: 'char_he', text: '来得正好！刚接到交警电话，环城路连环追尾，二十分钟后到一批伤员。你们床旁机推得动吧？今晚可能要连轴转。', next: 'n3_er2' },
      n3_er2: { speaker: 'sys', text: '【帮急诊做点准备？】', sprite: 'char_he', choices: [
        { text: '帮忙把抢救车、平车归位（⚡-1）', next: 'n3_er3a', effect: { gold: 30, heart: 1, flag: 'he_friend', ap: -1 }, cond: { ap: 1 }, tag: 'good', risk: { chance: 0.3, next: 'n3_er3r', effect: { heart: -1 } } },
        { text: '顺口问：床旁机拍片和机房拍有什么区别？', next: 'n3_er3b', effect: { skill: 1 }, tag: 'good' },
      ]},
      n3_er3a: { speaker: 'he', sprite: 'char_he', text: '够意思！今晚要是忙不过来我喊你。……对了，进抢救区记得穿铅衣，床旁机曝光的时候整个屋子都在散射线里泡着，跟机房里隔着铅玻璃可不一样。', next: 'n3_er4' },
      n3_er3b: { speaker: 'he', sprite: 'char_he', text: '区别大了。床旁机没有滤线栅，功率也小，人还没法摆标准体位——所以床旁片天生就灰蒙蒙的。你们科的师傅说，那是散射线闹的，X光在病人身体里撞来撞去，横着出来的光子把图像「蒙」上了一层雾。', next: 'n3_er4' },
      n3_er4: { speaker: 'sys', text: '你回到科室。二十分钟后，这条信息救了场。（回到科室）', next: 'n3_hub' },
      n3_er3r: { speaker: 'sys', sprite: 'char_he', text: '（意外）你把抢救车推回位，顺手把散落的注射器收进抽屉——可放错了格子。半小时后抢救演练，护士长当着全急诊的面点名：「谁动的抢救车？」小何挤挤眼替你认了，回头小声说：「没事儿。对了，进抢救区记得穿铅衣——床旁机曝光时整个屋子都在散射线里泡着。」（人心-1）', next: 'n3_er4' },
      n3_arc0: { bg: 'bg_archive', speaker: 'sys', text: '片库的铁门虚掩着——那把挂锁不见了。你推开门，月光从高窗照进来，照亮一排排码到天花板的片袋。', next: 'n3_arc1' },
      n3_arc1: { speaker: 'sys', text: '【四处看看？】', choices: [
        { text: '翻看架子上的旧片袋', next: 'n3_arc2', effect: { flag: 'archive_film' }, cond: { notFlag: 'archive_film' }, tag: 'good' },
        { text: '🗝️ 用黄铜钥匙开角落的小铁柜', next: 'n3_cab0', cond: { item: 'key', notFlag: 'archive_cab' }, effect: { flag: 'archive_cab' }, tag: 'good' },
        { text: '算了，不属于自己的地方少待', next: 'n3_hub' },
      ]},
      n3_arc2: { speaker: 'me', text: '大多是八九十年代的胸片、骨片，片袋边缘印着年份。……咦？最底层塞着一个没有登记号的牛皮纸袋，摸上去比别的都厚。', next: 'n3_arc3' },
      n3_arc3: { speaker: 'me', image: 'item_film', text: '（抽出来对着月光）里面是一张老胶片和一张申请单存根。胶片上的影像模糊发黄，隐约是胸廓的轮廓，却又像蒙着一层雾。存根日期：1998年11月。申请人签名栏——被人撕掉了一半。', next: 'n3_arc4' },
      n3_arc4: { speaker: 'sys', text: '远处传来电梯到达的叮咚声。你把片袋塞回原处，退出片库，心跳得比脚步快。（线索：1998年的无名胶片）', next: 'n3_hub' },
      n3_cab0: { speaker: 'sys', text: '黄铜钥匙转了两圈，小铁柜「吱呀」开了。', next: 'n3_cab1' },
      n3_cab1: { speaker: 'me', image: 'item_screen', text: '里面没有金银财宝，只有：两块发黄的增感屏、一包铅字号码、一小叠现金和一张字条——「屏片时代的老伙计们，退休了。钨酸钙屏，见X光就发荧光，当年全靠它把X光变成光，胶片才感得上光。」', effect: { gold: 80 }, next: 'n3_cab2' },
      n3_cab2: { speaker: 'sys', image: 'item_screen', text: '你拿起一块增感屏，在黑暗里它沉默着。上一代影像科医生的全部骄傲，就锁在这个小柜子里。（你把柜子锁回去，起身回到片架之间）', effect: { skill: 1 }, next: 'n3_arc1' },
      n3_rest0: { bg: 'bg_breakroom', speaker: 'sys', sfx2: 'vox_jiang', text: '值班室的对讲机突然「滋啦」响了：「影像科影像科，后勤老蒋。三楼走廊灯管又坏了两根，另外你们检查室铅门的密封条老化了，我报了采购，明后天换。」', sfx: 'radio', radio: 'char_jiang', next: 'n3_rest1' },
      n3_rest1: { speaker: 'sys', text: '【拿起对讲机回话？】', radio: 'char_jiang', choices: [
        { text: '「蒋师傅辛苦！要不要我搭把手换灯管？」（⚡-1）', next: 'n3_rest2a', effect: { gold: 20, heart: 1, flag: 'jiang_friend', ap: -1 }, cond: { ap: 1 }, tag: 'good', risk: { chance: 0.3, next: 'n3_rest2r', effect: { gold: -25 } } },
        { text: '「收到。铅门老化会有影响吗？」', next: 'n3_rest2b', effect: { skill: 1 }, tag: 'good' },
      ]},
      n3_rest2a: { speaker: 'sys', sprite: 'char_jiang', text: '你在走廊帮老蒋扶梯子，他絮絮叨叨讲了半小时楼里哪根管子几岁了。临走他塞给你一瓶冰红茶：「夜班娃娃都不容易。」（回到科室）', next: 'n3_hub' },
      n3_rest2r: { speaker: 'sys', sprite: 'char_jiang', text: '（意外）拆旧灯管时玻璃碴划破了手指。老蒋翻出一条创可贴，又硬拉你去护士站消了毒：「夜班娃娃，手就是饭碗，下回戴手套！」（金币-25）', next: 'n3_rest2a' },
      n3_rest2b: { speaker: 'jiang', radio: 'char_jiang', sfx: 'vox_jiang', text: '「会漏射线呀。防护材料都讲铅当量——多厚的材料顶多厚的铅。门缝的橡胶条里掺了铅粉，老化了就等于墙上开了条缝。你们操作间虽然隔着，防的就是万一嘛。行了，挂了。」（回到科室）', next: 'n3_hub' },

      n3_case0: { bg: 'bg_control', speaker: 'sys', text: '晚上十点。分诊台电话响了：「急诊，胸痛的小伙子，马上送上来！」', sfx: 'ring', next: 'n3_s4' },
      n3_s4: { bg: 'bg_xrayroom', speaker: 'thin', sprite: 'pat_thin', sfx: 'vox_thin', text: '医生……我胸口突然像被针扎，喘不上气……打着篮球呢，就这么突然……', next: 'n3_s5' },
      n3_s5: { speaker: 'me', text: '瘦高体型、年轻人、突发胸痛呼吸困难——这个组合在你脑子里敲响了警钟：高度怀疑自发性气胸。拍张胸片证实。', sprite: 'pat_thin', next: 'n3_s6' },
      n3_s6: { speaker: 'sys', text: '【他疼得直不起腰。怎么拍？】', sprite: 'pat_thin', choices: [
        { text: '让他躺下拍卧位片，舒服点', next: 'n3_s7a', effect: { skill: -1, flag: 'n3_wrong' }, tag: 'bad' },
        { text: '扶他站稳，拍站立后前位胸片', next: 'n3_s7b', effect: { skill: 2 }, tag: 'good' },
      ]},
      n3_s7a: { speaker: 'zhou', sprite: 'char_zhou', text: '气胸躺下拍？气体会往前散开贴在胸壁上，卧位片上常常看不清楚。气体往上跑——站起来拍，气全聚在肺尖，一眼就能看见。扶他一把，站着拍。', next: 'n3_s8' },
      n3_s7b: { speaker: 'me', text: '游离气体往上跑——站立位时胸腔里的气会聚到肺尖，片子上看得最清楚。哪怕他难受，也得扶稳了站着拍这一张。', next: 'n3_s8' },
      n3_s8: { speaker: 'sys', text: '「嘀——咔！」曝光完成。你扶他坐下喘口气，抽出IP板。', sfx: 'xray', next: 'n3_s8r' },
      n3_s8r: { speaker: 'sys', text: '你把板子送进隔壁扫描仪，按下读取键——这张片子容不得第二遍，他经不起再吃一倍的剂量。', readout: 'xray_pneumo', next: 'n3_s9' },
      n3_s9: { speaker: 'me', text: '胸片出来了：左侧肺野外带一片异常的「黑」，黑区里看不到肺纹理，边缘还能看见一条细细的白线——那是被压缩的肺的边缘。', image: 'xray_pneumo', next: 'n3_s10' },
      n3_s10: { speaker: 'sys', text: '【这片「特别黑」的区域说明什么？】', image: 'xray_pneumo', choices: [
        { text: '肺被胸腔里的气体压缩了——气胸', next: 'n3_s11a', effect: { skill: 2 }, tag: 'good' },
        { text: '左肺大面积发炎实变', next: 'n3_s11b', effect: { skill: -1, flag: 'n3_wrong' }, tag: 'bad' },
      ]},
      n3_s11a: { speaker: 'zhou', sprite: 'char_zhou', image: 'xray_pneumo', text: '对。气体几乎不挡X光，片子上就黑；肺被压瘪了，纹理全没了。自发性气胸，瘦高个小伙子的「专利」。马上通知胸外科，做胸腔闭式引流。', next: 'n3_s12' },
      n3_s11b: { speaker: 'zhou', sprite: 'char_zhou', image: 'xray_pneumo', text: '看反了——发炎实变是「白」，这片区是「黑」：气体不挡X光，黑得发亮，还没有肺纹理。这是气胸，肺被压瘪了。马上通知胸外科！', next: 'n3_s12' },
      n3_s12: { speaker: 'thin', sprite: 'pat_thin', text: '谢谢医生……刚才真的以为自己要憋死了……', next: 'n3_s13' },
      n3_s13: { speaker: 'sys', text: '【对他说点什么？】', sprite: 'pat_thin', choices: [
        { text: '「别怕，引流管一放你就能顺畅呼吸了。以后瘦了别硬扛剧烈运动。」', next: 'n3_gossip0', effect: { heart: 1, flag: 'n3_kind' }, tag: 'good' },
        { text: '「胸外科在八楼，去吧。」', next: 'n3_gossip0', tag: 'neutral' },
      ]},
      n3_gossip0: { bg: 'bg_breakroom', speaker: 'sys', text: '安顿好小伙子，你回值班室扒了口饭。老周在角落泡方便面，热气糊了他半张脸。', next: 'n3_gossip1' },
      n3_gossip1: { speaker: 'zhou', sprite: 'char_zhou', text: '说个乐子。超声科上个月耦合剂用量全院第一，被财务通报「加强成本管控」。你说，做超声的省耦合剂，跟让咱拍片省X线，是不是一个意思？', next: 'n3_gossip2' },
      n3_gossip2: { speaker: 'zhou', text: '院里例会又研究CT了。那台老机器球管烧了小半年，厂家说配件停产，维修报价顶半台新机——院长拍了板：不修，直接换。可新机器到现在还没影。倒是有人出主意，先租台移动CT车应应急，一算租金，又没人吭声了。', next: 'n3_gossip3' },
      n3_gossip3: { speaker: 'zhou', text: '（他忽然停下筷子，看着窗外）问你个事。要是有人看不起病，疼得直不起腰——你说，机器认钱，还是认人？……算了，当我没说。眯一会儿吧，后半夜还长。', next: 'n3_trauma0' },
      n3_trauma0: { speaker: 'sys', text: '凌晨两点，急诊科来电话——连环追尾的伤员到了，其中一位无法搬动，需要床旁胸片。', sfx: 'ring', phone: 'char_he', next: 'n3_trauma1' },
      n3_trauma1: { bg: 'bg_corridor', speaker: 'he', sprite: 'char_he', sprite2: 'pat_trauma', image: 'machine_mobile', sfx: 'groan_man', text: '就靠你了！病人躁动，躺不平，机器我只能推到床边这个角度。放心，这台是全院唯一一台移动DR——平板探测器直连，拍完直接在这儿出图，不用抱着板子跑扫描仪！', next: 'n3_trauma2' },
      n3_trauma2: { speaker: 'sys', sprite: 'pat_trauma', text: '床旁机曝光。「嘀——咔！」图像当场传到便携屏幕上——', sfx: 'xray', next: 'n3_trauma3' },
      n3_trauma3: { speaker: 'me', sprite: 'pat_trauma', image: 'xray_fog', text: '（皱眉）整张片子灰蒙蒙的，像蒙了一层雾，对比度很差。肺野边缘糊成一片。', next: 'n3_trauma4' },
      n3_trauma4: { speaker: 'sys', image: 'xray_fog', text: '【图像发灰，最可能的原因是？】', choices: [
        { text: '病人躁动，运动伪影', next: 'n3_trauma5b', effect: { skill: -1 }, tag: 'bad' },
        { text: '床旁机没有滤线栅，病人体内的散射线把图像「蒙」住了', next: 'n3_trauma5a', effect: { skill: 2 }, tag: 'good' },
        { text: '床旁机坏了，拍不了', next: 'n3_trauma5c', effect: { skill: -1 }, tag: 'bad' },
      ]},
      n3_trauma5a: { speaker: 'me', image: 'xray_fog', text: '对。X光穿过病人时，一部分光子发生康普顿散射、改变方向，四面八方的散射光子都打到探测器上，就成了这层均匀的「灰雾」。床旁没有滤线栅吸收它们，只能我们自己想办法。', next: 'n3_trauma6a' },
      n3_trauma5b: { speaker: 'he', sprite: 'char_he', text: '他是躁动，可伪影是局部的模糊拖影，不会整张片均匀发灰。你再想想——什么东西会让整张片蒙雾？（提示：光子在病人体内会「拐弯」）', next: 'n3_trauma6b' },
      n3_trauma5c: { speaker: 'he', sprite: 'char_he', text: '别急着赖机器呀，它昨天刚保养过。均匀发灰、对比度下降——你们老周没教过散射吗？（提示：光子在病人体内会「拐弯」）', next: 'n3_trauma6b' },
      n3_trauma6a: { speaker: 'sys', text: '【对策？】', choices: [
        { text: '把照射野缩到刚好包住胸部，再补拍一张', next: 'n3_trauma7a', effect: { skill: 1 }, tag: 'good' },
        { text: '加大剂量硬怼，把灰雾「压」下去', next: 'n3_trauma7b', effect: { skill: -1, flag: 'n3_wrong' }, tag: 'bad' },
      ]},
      n3_trauma6b: { speaker: 'sys', text: '你想起来了：康普顿散射——X光子在病人体内改变方向，散射光子均匀打在探测器上，就是这层灰雾。', next: 'n3_trauma6a' },
      n3_trauma7a: { speaker: 'sys', text: '你收紧准直器，照射野缩到刚好覆盖胸部——散射的来源少了，补拍的片子清楚了一大截：左侧肋骨骨折，肺挫伤待排。小何比了个大拇指。', effect: { gold: 80 }, next: 'n3_s14' },
      n3_trauma7b: { speaker: 'he', sprite: 'char_he', text: '剂量翻倍，灰雾没下去多少，病人还白吃了辐射。老周知道了要骂人的——散射线是「方向乱了」，不是「数量不够」，加剂量连灰雾一起加。快缩小照射野重拍。', next: 'n3_trauma7a2' },
      n3_trauma7a2: { speaker: 'sys', text: '你收紧准直器补拍一张，图像终于能看了：左侧肋骨骨折。小何拍拍你肩膀：「学费交一次就够了。」', next: 'n3_s14' },
      n3_s14: { speaker: 'sys', text: '后半夜平安无事。天亮前，你在科室转了一圈做收尾——', next: 'n3_s15' },
      n3_s15: { speaker: 'me', text: '（你的目光落在控制室那扇大观察窗上。窗户那头黑漆漆的，是CT室——那台老CT静静趴在里面，机架上贴着「故障停用」的条子，边角都卷起来了。）', next: 'n3_s16' },
      n3_s16: { speaker: 'zhou', sprite: 'char_zhou', text: '看什么呢？……哦，那台老伙计啊。开春那会儿球管烧了，厂家说配件早停产，修一下顶半台新机。院长放了话：不修了，直接换新的——采购流程走了小半年，还没走完。', next: 'n3_s17' },
      n3_s17: { speaker: 'me', text: 'CT……那台机器要是还转着，今晚那个胸痛的小伙子，怕的不是气胸而是夹层，扫一眼就见分晓；那个大叔摔的不是胳膊而是头，也不用赌——它趴窝的这几个月，这间科室能守住多少夜？', sprite: 'char_zhou', next: 'n3_s18' },
      n3_s18: { speaker: 'zhou', sprite: 'char_zhou', text: '（难得没有毒舌）等批文吧。或者等奇迹。……打卡下班，今晚干得不错。', next: 'n3_s19' },
      n3_s19: { speaker: 'sys', text: '【今夜结算】诊疗收入 +300 金币', effect: { gold: 300 }, stamp: true, next: 'n3_end' },
      n3_end: { end: true },
    },
  },
  // ================= 第 4 夜 =================
  {
    id: 4,
    title: '第 4 夜',
    subtitle: '潜影',
    start: 'n4_s0',
    steps: {
      n4_s0: { bg: 'bg_control', speaker: 'sys', text: '第四夜。你已经是科里半个熟脸了，保洁阿姨都会跟你点头。', next: 'n4_s1' },
      n4_s1: { speaker: 'sys', text: '【今日打卡】', choices: [{ text: '📮 打卡上岗', next: 'n4_s2', effect: { gold: 50 } }] },
      n4_s2: { speaker: 'sys', text: '「咔哒」——打卡成功。金币 +50。', sfx: 'stamp', next: 'n4_s3' },
      n4_s3: { speaker: 'zhou', sprite: 'char_zhou', text: '今晚我去医务科开个会，前半夜科里你盯着。别紧张，有事先想三步再动手，拿不准就翻书。……对了，今天设备科搞质控，厂家也有人来了，楼里人多嘴杂，你自己有数就行。', next: 'n4_s4' },
      n4_s4: { speaker: 'tang', sprite: 'char_tang', text: '（老周走后）他今天怎么婆婆妈妈的……不管了，开诊前老规矩，你随意转转！', effect: { ap: 3 }, next: 'n4_hub' },

      n4_hub: { speaker: 'sys', text: '【自由行动 · 去哪转转？】（行动力见顶部 ⚡）', choices: [
        { text: '🛒 小卖部逛逛（不耗行动力）', next: '@shop' },
        { text: '📖 翻翻值班室那本旧书（不耗行动力）', next: '@book' },
        { text: '💻 去信息科找小雷（⚡-1）', next: 'n4_lei0', effect: { ap: -1, flag: 'n4_lei' }, cond: { ap: 1, notFlag: 'n4_lei' } },
        { text: '🔧 去设备科围观质控（⚡-1）', next: 'n4_fan0', effect: { ap: -1, flag: 'n4_fan' }, cond: { ap: 1, notFlag: 'n4_fan' } },
        { text: '💼 走廊上那位西装女士好像找你有事（⚡-1）', next: 'n4_wen0', effect: { ap: -1, flag: 'n4_wen' }, cond: { ap: 1, notFlag: 'n4_wen' } },
        { text: '🩺 去检查室开工', next: 'n4_case0' },
      ]},
      n4_lei0: { bg: 'bg_corridor', speaker: 'lei', sprite: 'char_lei', text: '是你！正好，我这阵子给PACS做巡检，你有什么要查的，趁我权限开着。', next: 'n4_lei1' },
      n4_lei1: { speaker: 'sys', text: '【查点什么？】', sprite: 'char_lei', choices: [
        { text: '查旧片库那张无名胶片——1998年11月的记录', next: 'n4_lei2a', cond: { flag: 'archive_film' }, effect: { flag: 'pacs_log' }, tag: 'good' },
        { text: '随便聊聊：PACS到底是干嘛的？', next: 'n4_lei2b', effect: { skill: 1, heart: 1 }, tag: 'good' },
        { text: '🍪 把零食礼包分他一半', next: 'n4_lei2c', cond: { item: 'snack' }, effect: { heart: 1, loseItem: 'snack' }, tag: 'good' },
      ]},
      n4_lei2a: { speaker: 'lei', sprite: 'char_lei', text: '1998年？那会儿还没PACS呢，全是胶片。……不过——（他敲了几下键盘，皱眉）怪了，你们科的工作站，最近几个月凌晨三点多有几次登录记录，用的还是老周的账号。打印记录？没有。就登录、看片、退出。', next: 'n4_lei3a' },
      n4_lei2b: { speaker: 'lei', sprite: 'char_lei', text: '你们拍完的片子，不再是胶片了，是一串数据——PACS就是管这些数据存哪、谁能看、怎么调的系统。你们科今晚每张片，最后都睡在我维护的服务器里。所以，对它客气点。', next: 'n4_lei3b' },
      n4_lei2c: { speaker: 'lei', sprite: 'char_lei', text: '哇，谢谢！信息科夜班就我一个人，平时连个说话的都没有……以后服务器机房随便你参观，虽然也没什么好看的哈哈。', next: 'n4_lei3b' },
      n4_lei3a: { speaker: 'me', text: '（凌晨三点、老周的账号、只看片不打印……你想起片库里那张没有登记号的胶片。这两件事之间，有一根你看不见的线。）', next: 'n4_lei4' },
      n4_lei3b: { speaker: 'sys', text: '和小雷道了别，你回到科室。', next: 'n4_hub' },
      n4_lei4: { speaker: 'sys', text: '小雷把登录日志截了张图发你：「别说是我查的啊。」（回到科室）', next: 'n4_hub' },
      n4_fan0: { bg: 'bg_corridor', speaker: 'fan', sprite: 'char_fan', text: '来得正好，搭把手扶梯子——今天测你们机器的固有滤过。', next: 'n4_fan1' },
      n4_fan1: { speaker: 'fan', sprite: 'char_fan', text: '球管射出来的X光谱是连续的，里头混着一堆低能光子——穿不透人体，只会平白增加病人剂量。玻璃管壁、绝缘油，再加一块附加滤过板，把这些软射线先滤掉，剩下的才拿去成像。我们拿铝片当尺子量它，叫铝当量。', effect: { skill: 1 }, next: 'n4_fan2' },
      n4_fan2: { speaker: 'fan', sprite: 'char_fan', text: '（拍拍老机器）再有两年它也该退了。听说主任在打报告换DR整机……换不换得起另说。哎，你没听见啊，我什么都没说。（+30金币扶梯费）', effect: { gold: 30, flag: 'dr_rumor' }, next: 'n4_hub' },
      n4_wen0: { bg: 'bg_corridor', speaker: 'wen', sprite: 'char_wen', sfx: 'vox_wen', text: '这位技师老师！我是厂家销售雯雯，正好今天跟设备科做质控——耽误您两分钟？（不由分说递上一本宣传册）', next: 'n4_wen1' },
      n4_wen1: { speaker: 'wen', sprite: 'char_wen', text: '你们科要是升级DR，探测器是核心，主流两种：非晶硅，间接型——X光先被碘化铯闪烁体转成可见光、再转成电信号，DQE高、密度分辨好，拍胸片首选；非晶硒，直接型——X光直接变电荷，中间没有光散射，空间分辨率最高，四肢关节、乳腺这类看细节的部位最合适。', next: 'n4_wen2' },
      n4_wen2: { speaker: 'sys', text: '【怎么接话？】', sprite: 'char_wen', choices: [
        { text: '认真听完，还追问了几个参数', next: 'n4_wen3a', effect: { skill: 1, flag: 'wen_card' }, tag: 'good' },
        { text: '「我们科CT趴窝小半年了，这事您得跟我们主任聊。」', next: 'n4_wen3b', effect: { flag: 'wen_card' } },
      ]},
      n4_wen3a: { speaker: 'wen', sprite: 'char_wen', text: '（眼睛一亮）您是今晚第一个问我DQE的技师！名片收好——真到招标那天，懂行的人替科室把关，才不会花冤枉钱。', next: 'n4_wen4' },
      n4_wen3b: { speaker: 'wen', sprite: 'char_wen', text: '（职业微笑）没关系，名片还是留您一张。设备这东西，买之前人人嫌贵，用上了人人嫌晚。', next: 'n4_wen4' },
      n4_wen4: { speaker: 'sys', text: '宣传册最后一页印着一行小字：「让每一毫安秒都值得。」（回到科室）', next: 'n4_hub' },

      n4_case0: { bg: 'bg_control', speaker: 'sys', text: '晚上十点。老周去市里开质控会了，走前撂下话：「今晚你主值，拍的片子先写初步印象，正式报告明早我来签——技师出图、医师签发，规矩不能乱。」第一位访客有些特别——体检科打电话来，说一位阿姨白天约了乳腺钼靶，临时有事没赶上，晚上自己摸过来了。', next: 'n4_case1' },
      n4_case1: { bg: 'bg_xrayroom', speaker: 'aunt', sprite: 'pat_aunt', sfx: 'vox_aunt', text: '医生，我是不是来得不是时候？白天单位实在走不开……要不您这儿随便给我拍一张？', next: 'n4_case2' },
      n4_case2: { speaker: 'me', text: '（看了一眼角落那台老伙计——钨靶的普通X光机。乳腺钼靶检查是专用设备，咱这儿还真没有。）', sprite: 'pat_aunt', next: 'n4_case3' },
      n4_case3: { speaker: 'sys', text: '【怎么办？】', sprite: 'pat_aunt', choices: [
        { text: '夜班没有钼靶机，先问清她的情况再安排', next: 'n4_case4a', effect: { skill: 1, heart: 1 }, tag: 'good' },
        { text: '就用老伙计给她拍一张，机器都是拍片的嘛', next: 'n4_case4b', effect: { skill: -1, flag: 'n4_wrong' }, tag: 'bad' },
        { text: '「我们拍不了，您请回吧。」', next: 'n4_case4c', effect: { heart: -1 }, tag: 'neutral' },
      ]},
      n4_case4a: { speaker: 'aunt', sprite: 'pat_aunt', text: '上次体检的大夫说我是「致密型乳腺」，让我半年复查一次……', next: 'n4_case5' },
      n4_case4b: { speaker: 'me', text: '你架起机器才想起白天书上的内容：乳腺钼靶用的是钼靶球管，管电压压得很低，利用钼的特征辐射——那两段能量刚好让脂肪、腺体这些软组织之间的差别在片子上拉开。而老伙计的高能硬射线打过去，软组织对比度根本拉不开，剂量还大。……你默默把机器关了。', next: 'n4_case4b2' },
      n4_case4b2: { speaker: 'me', text: '（诚恳地）阿姨，今晚这台机器真不适合您，我帮您约白天钼靶门诊。（幸好及时停手了。）', next: 'n4_case5' },
      n4_case4c: { speaker: 'sys', text: '阿姨愣了一下，小声嘀咕着「白跑一趟」走了。小唐欲言又止：「其实……你可以帮她约明天的钼靶门诊呀。」', next: 'n4_ghost0' },
      n4_case5: { speaker: 'me', image: 'machine_mammo', text: '致密型乳腺——腺体多脂肪少，钼靶片子上白茫茫一片，病灶容易藏起来；这种情况超声反而看得更清。所以临床上钼靶加超声是黄金组合。', next: 'n4_case6' },
      n4_case6: { speaker: 'me', image: 'machine_mammo', text: '（你翻出宣传册，指着上面的钼靶机照片给她看。）阿姨您看，钼靶机长这样——球管是钼靶、电压压得低，还有块压迫板把乳腺轻轻压住摊薄，就是专门给乳腺软组织设计的。咱夜班这台是拍骨头异物的，硬拍是对您不负责。我帮您约好白天的钼靶门诊，再把「致密型记得加个超声」写在便签上。', next: 'n4_case7' },
      n4_case7: { speaker: 'aunt', sprite: 'pat_aunt', text: '哎，原来机器还分这么多讲究！谢谢你啊小医生，讲得比白天门诊还明白。', effect: { heart: 1, flag: 'n4_kind' }, next: 'n4_gossip0' },
      n4_gossip0: { speaker: 'sys', text: '送走阿姨，小唐凑过来，神神秘秘地压低了声音。', next: 'n4_gossip1' },
      n4_gossip1: { speaker: 'tang', sprite: 'char_tang', text: '欸，你听说过没——老夜班的人说，凌晨路过旧片库，能听见里面哗啦哗啦翻片子的声音。可那屋子，锁了二十年啦。', next: 'n4_gossip2' },
      n4_gossip2: { speaker: 'tang', text: '还有信息科那个小雷，半夜不睡觉在PACS里挖数据，被网管逮住警告了一回。他说他在找「很有年代感的东西」……你说他找啥呢？', next: 'n4_gossip3' },
      n4_gossip3: { speaker: 'tang', text: '对了，听说医务科最近在抽查各科的登记本，一页都不能少。咱们科的本子……应该都在吧？（她忽然自己打了个寒颤）', next: 'n4_gossip4' },
      n4_gossip4: { speaker: 'tang', text: '最后说个气人的：心内科DSA昨晚连做三台急诊介入，人家一个月奖金顶咱们仨月。唉，羡慕完还得干活——欸，门口是不是来病人了？', next: 'n4_ghost0' },
      n4_ghost0: { speaker: 'sys', sprite: 'pat_regular', text: '说曹操曹操到——急诊来了位常规胸片。你照常曝光、上传——', next: 'n4_ghost1' },
      n4_ghost1: { speaker: 'sys', sprite: 'pat_regular', text: '「嘀——咔！」曝光完成。你抽出IP板。', sfx: 'xray', next: 'n4_ghost1r' },
      n4_ghost1r: { speaker: 'sys', text: 'IP板送进隔壁扫描仪，激光一行行扫过板面——', readout: 'xray_ghost', next: 'n4_ghost2' },
      n4_ghost2: { speaker: 'me', text: '图像出来了。可是……片子边缘，浮着一层淡淡的、不属于这位病人的影子。像一个模糊的人形，叠在肺野外侧。', image: 'xray_ghost', next: 'n4_ghost3' },
      n4_ghost3: { speaker: 'tang', sprite: 'char_tang', text: '（声音发飘）那、那是什么……今晚就咱俩，前面没别人拍过片啊……', image: 'xray_ghost', next: 'n4_ghost4' },
      n4_ghost4: { speaker: 'sys', text: '【「残影」是怎么回事？】', image: 'xray_ghost', choices: [
        { text: '沉着排查：先确认这是成像链上的问题，不是「人」', next: 'n4_ghost5a', effect: { skill: 2 }, tag: 'good' },
        { text: '跟小唐一起头皮发麻：不会真是片库那位吧……', next: 'n4_ghost5b', tag: 'neutral' },
      ]},
      n4_ghost5a: { speaker: 'me', text: '（你想起老范白天的话：扫描仪那根擦除灯管老化了，读完要多擦一遍。）存储荧光材料的成像板上，上一次的「潜影」如果没被彻底擦除，下次读出就会留下淡淡的叠影。科里好几块IP板轮换着用，今晚前面的片子都干净——说明只有这一块板子，在我们不知情的时候被人拍过，而且那人赶时间，老化的灯管只草草擦了一遍就塞回了片盒。这不是灵异事件，是有人摸黑用过机器，没按流程收尾。', next: 'n4_ghost6' },
      n4_ghost5b: { speaker: 'tang', sprite: 'char_tang', text: '呸呸呸！（她拍了自己一下）……不对，等等——老范说过，擦除灯管老了，板子擦不干净就会留「上一位的影子」。可今晚前面的片子都正常啊？IP板是轮换着用的……那就是说，偏偏这一块板子，在我们不知道的时候被人用过，用完还赶时间没擦干净？', effect: { skill: 1 }, next: 'n4_ghost6' },
      n4_ghost6: { speaker: 'sys', text: '你调出今晚的图像列表：一切正常，每一块板子的使用记录都对得上号——除了这一块。那么它上面的「上一位」，是谁、在什么时候拍的？', next: 'n4_ghost7' },
      n4_ghost7: { speaker: 'sys', text: '【联想到什么了吗？】', choices: [
        { text: '（想起小雷查到的记录：凌晨3点、老周的账号、只看片不打印）', next: 'n4_ghost8a', cond: { flag: 'pacs_log' }, tag: 'good' },
        { text: '先记下这个现象，明天再说', next: 'n4_ghost8b', tag: 'neutral' },
      ]},
      n4_ghost8a: { speaker: 'me', text: '凌晨三点。老周的账号。没有登记、没有打印、没有收费的片子。如果那时拍的是真人——板子上的残影、片库里1998年的无名胶片、那个问「老片子」的男人……线头好像都攥在同一个人手里。', effect: { flag: 'zhou_secret' }, next: 'n4_ghost9a' },
      n4_ghost8b: { speaker: 'sys', text: '你把残影片存进了一个单独文件夹，命名为「？」。直觉告诉你，这事还没完。', effect: { flag: 'ghost_kept' }, next: 'n4_end0' },
      n4_ghost9a: { speaker: 'sys', text: '就在这时，门口传来钥匙声——开完会的老周提前回来了。你和小唐对视一眼，默契地切换了屏幕。', next: 'n4_ghost10' },
      n4_ghost10: { speaker: 'zhou', sprite: 'char_zhou', text: '（扫了一眼操作台，目光在屏幕上停了半秒）……今晚没什么事吧？早点收尾，累了就早点回去。（他转身进了里间。你注意到，他的白大褂下摆沾着一点灰——像是不久前去过很久没人去的地方。）', next: 'n4_end0' },
      n4_end0: { speaker: 'sys', text: '【今夜结算】诊疗收入 +280 金币', effect: { gold: 280 }, stamp: true, next: 'n4_end' },
      n4_end: { end: true },
    },
  },
  // ================= 第 5 夜 =================
  {
    id: 5,
    title: '第 5 夜',
    subtitle: '守夜人',
    start: 'n5_s0',
    steps: {
      n5_s0: { bg: 'bg_control', speaker: 'sys', text: '第五夜。这一周最后一班。你推开科室大门的时候，已经能听出老伙计运转的声音今天有点哑。', next: 'n5_s1' },
      n5_s1: { speaker: 'sys', text: '【今日打卡】', choices: [{ text: '📮 打卡上岗', next: 'n5_s2', effect: { gold: 50 } }] },
      n5_s2: { speaker: 'sys', text: '「咔哒」——打卡成功。金币 +50。', sfx: 'stamp', next: 'n5_s3' },
      n5_s3: { speaker: 'tang', sprite: 'char_tang', text: '最后一夜！今天楼里可热闹了：厂家工程师来给老伙计做年度保养，还有个背皮包的外人在走廊晃悠半天了。开诊前你随意。', effect: { ap: 3 }, next: 'n5_hub' },

      n5_hub: { speaker: 'sys', text: '【自由行动 · 去哪转转？】（行动力见顶部 ⚡）', choices: [
        { text: '🛒 小卖部逛逛（不耗行动力）', next: '@shop' },
        { text: '📖 翻翻值班室那本旧书（不耗行动力）', next: '@book' },
        { text: '🔧 围观厂家工程师保养老伙计（⚡-1）', next: 'n5_kai0', effect: { ap: -1, flag: 'n5_kai' }, cond: { ap: 1, notFlag: 'n5_kai' } },
        { text: '💼 走廊上那个背皮包的人朝你招手（⚡-1）', next: 'n5_bai0', effect: { ap: -1, flag: 'n5_bai' }, cond: { ap: 1, notFlag: 'n5_bai' } },
        { text: '🗄️ 再去一趟旧片库（⚡-1）', next: 'n5_arc0', effect: { ap: -1, flag: 'n5_arc' }, cond: { ap: 1, notFlag: 'n5_arc', flag: 'archive_film' } },
        { text: '🔧 后勤老蒋在走廊换灯管，去打个招呼', next: 'n5_jiang0', effect: { flag: 'n5_jiang' }, cond: { flag: 'jiang_friend', notFlag: 'n5_jiang' }, tag: 'good' },
        { text: '🏃 小何说急诊有人给你留了东西', next: 'n5_qian0', effect: { flag: 'n5_qian' }, cond: { flag: 'qian_helped', notFlag: 'n5_qian' }, tag: 'good' },
        { text: '🧰 老范叫你去设备科一趟', next: 'n5_fan0', effect: { flag: 'n5_fan' }, cond: { flag: 'fan_friend', notFlag: 'n5_fan' }, tag: 'good' },
        { text: '💻 小雷抱着笔记本在科门口探头', next: 'n5_lei0', effect: { flag: 'n5_lei' }, cond: { flag: 'met_lei', notFlag: 'n5_lei' }, tag: 'good' },
        { text: '🩺 去检查室开工', next: 'n5_case0' },
      ]},
      n5_jiang0: { bg: 'bg_corridor', speaker: 'jiang', sprite: 'char_jiang', sfx: 'vox_jiang', text: '哟，影像科的娃娃！你们那铅门密封条今天换上新的了，走廊灯管也换了——上回多亏你搭手。拿着，冰红茶，别嫌寒碜。', next: 'n5_jiang1' },
      n5_jiang1: { speaker: 'sys', sprite: 'char_jiang', text: '你拧开红茶喝了一口，甜的。整层楼的灯都亮堂堂的。（人心+1，回到大厅）', image: 'item_tea', effect: { heart: 1 }, next: 'n5_hub' },
      n5_qian0: { speaker: 'he', sprite: 'char_he', text: '欸，正好要找你！前两天工地摔伤那位大叔，专门打急诊电话过来——说你写的受伤说明一次就过了审，报销顺顺当当，非让我们把这袋苹果捎给你。', next: 'n5_qian1' },
      n5_qian1: { speaker: 'sys', sprite: 'char_he', text: '苹果又脆又甜。小何咬着一个，含混不清地学给你听：「他说你是好人呐。」（人心+1，回到大厅）', image: 'item_apple', effect: { heart: 1 }, next: 'n5_hub' },
      n5_fan0: { speaker: 'fan', sprite: 'char_fan', text: '来得正好。报废柜里清出一批老家伙，我瞅着这个你能用上——（他翻出一副老式铅橡胶眼镜）以前的医生拍片就戴这个。拿去，摆你们操作台上，也算个念想。', next: 'n5_fan1' },
      n5_fan1: { speaker: 'sys', sprite: 'char_fan', text: '铅眼镜沉甸甸的，镜腿上刻着模糊的年份：1987。老范摆摆手：「报废品，走不了账，别声张。」（家业+1，回到大厅）', image: 'item_glasses', effect: { wealth: 1 }, next: 'n5_hub' },
      n5_lei0: { speaker: 'lei', sprite: 'char_lei', text: '嘿！我把你这几晚遇上的病例整理成错题本了——双环征、正侧位、立位气胸……喏，都在这，PACS里我也给你备份了一份，考前翻翻。', next: 'n5_lei1' },
      n5_lei1: { speaker: 'sys', sprite: 'char_lei', text: '你翻了翻，每一页都配了示意图。信息科的朋友，靠谱。（技术+1，回到大厅）', image: 'item_notebook', effect: { skill: 1 }, next: 'n5_hub' },
      n5_kai0: { bg: 'bg_xrayroom', speaker: 'kai', sprite: 'char_kai', sfx: 'vox_kai', text: '你好，厂家售后，阿凯。正好，带你过一遍这台机器的年度保养——你们平时也要会做日检。', next: 'n5_kai1' },
      n5_kai1: { speaker: 'kai', sprite: 'char_kai', text: '先看球管热容量曲线。电子撞靶，99%的动能变成热量，就靠旋转阳极把这摊热量摊开、散掉。连续曝光得给机器喘息，热容量报警不是闹着玩的——硬扛几次，靶面就熔出坑了，这台机器也就走到头了。', effect: { skill: 1 }, next: 'n5_kai2' },
      n5_kai2: { speaker: 'kai', sprite: 'char_kai', text: '再查滤过板有没有移位、灯丝电流稳不稳——灯丝电流管着电子的产量，也就是管电流的大小；管电压管着电子冲多快，也就是X光的穿透力。一个管「量」，一个管「质」。（他递给你一张保养单）来，帮我打勾。', next: 'n5_kai3' },
      n5_kai3: { speaker: 'sys', text: '【帮忙做保养？】', sprite: 'char_kai', choices: [
        { text: '认真跟完一整套流程', next: 'n5_kai4a', effect: { durability: 10, gold: 50, skill: 1, flag: 'kai_friend' }, tag: 'good' },
        { text: '看个大概就回科室了', next: 'n5_hub' },
      ]},
      n5_kai4a: { speaker: 'kai', sprite: 'char_kai', text: '好苗子。记住，机器不会说话，它的「不舒服」全写在参数里——听得懂参数的人，才配让它多活几年。（回到科室）', next: 'n5_hub' },
      n5_bai0: { bg: 'bg_corridor', speaker: 'bai', sprite: 'char_bai', sfx: 'vox_bai', text: '小兄弟！鄙人老白，做配件生意的。你们这台老机器，球管快到寿了吧？原厂一根球管多少钱你知道不？我这儿同规格第三方件，半价！', next: 'n5_bai1' },
      n5_bai1: { speaker: 'bai', sprite: 'char_bai', text: '（压低声音）别听厂家吓唬人，什么质保协议，都是生意。我这管子装在隔壁县医院跑了两年了，啥事没有。今晚你点头，明天就发货，200金币，原厂要400！', next: 'n5_bai2' },
      n5_bai2: { speaker: 'sys', text: '【怎么答复？】', sprite: 'char_bai', choices: [
        { text: '买！200金币一根，给科里省一半钱', next: 'n5_bai3a', effect: { gold: -200, durability: 25, flag: 'bai_tube' }, cond: { gold: 200 }, tag: 'neutral' },
        { text: '「球管是整机的命门，第三方件没有原厂匹配测试，我不敢签。」', next: 'n5_bai3b', effect: { skill: 1, wealth: 1 }, tag: 'good' },
        { text: '「150卖不卖？卖我就冒险试一根。」（需要人心够熟）', next: 'n5_bai3c', cond: { flag: 'he_friend', gold: 150 }, effect: { gold: -150, durability: 25, flag: 'bai_tube' }, tag: 'neutral' },
      ]},
      n5_bai3a: { speaker: 'bai', sprite: 'char_bai', text: '痛快！……（他走后，老周不知什么时候站在你身后，慢悠悠地说：「便宜件不是不能买，是坏了没人兜底——希望咱运气好吧。」）', next: 'n5_hub' },
      n5_bai3b: { speaker: 'bai', sprite: 'char_bai', text: '（讪笑）哟，还是个懂行的。得，买卖不成仁义在。（他背起皮包走了。老范在不远处朝你点了点头。）', next: 'n5_hub' },
      n5_bai3c: { speaker: 'bai', sprite: 'char_bai', text: '150？！……行吧行吧，交个朋友！（你想起小何说过这家供应商的东西县医院确实在用，赌一把。老周知道了，只说了四个字：「记账。盯着。」）', next: 'n5_hub' },
      n5_arc0: { bg: 'bg_archive', speaker: 'sys', text: '片库今晚又锁上了。不过上次来时你留意过，铁门的门轴早锈了，用力一推能错开一道缝——你侧身挤了进去。月光从高窗照进来，你径直走向最里侧的书架。', next: 'n5_arc1' },
      n5_arc1: { speaker: 'me', text: '书架后面果然还藏着一格空间：一个齐腰高的旧柜子，柜门交叉贴着两张封条，纸已发黄变脆。封条上的日期：1999年1月。就在那张无名胶片登记的两个月后。柜门上没有挂锁，只有一个形状奇特的锁孔，像是什么图案的一半。', effect: { flag: 'archive_sealed' }, next: 'n5_arc2' },
      n5_arc2: { speaker: 'sys', text: '封条边缘下露出一角标签，只能看清三个字：「……周……存」。你把看到的都记在了手机备忘录里。（这条线索，先押在这里——也许下一个章节，会有打开它的钥匙。）', next: 'n5_arc3' },
      n5_arc3: { speaker: 'sys', text: '【临走前，还有什么在意的吗？】', choices: [
        { text: '🗝️ 角落里那个小铁柜——用黄铜钥匙试试', next: 'n5_cab0', cond: { item: 'key', notFlag: 'archive_cab' }, effect: { flag: 'archive_cab' }, tag: 'good' },
        { text: '没了，离开片库', next: 'n5_hub' },
      ]},
      n5_cab0: { speaker: 'sys', text: '你回到门口那个角落，黄铜钥匙转了两圈，小铁柜「吱呀」开了。', next: 'n5_cab1' },
      n5_cab1: { speaker: 'me', image: 'item_screen', text: '里面没有金银财宝，只有：两块发黄的增感屏、一包铅字号码、一小叠现金和一张字条——「屏片时代的老伙计们，退休了。钨酸钙屏，见X光就发荧光，当年全靠它把X光变成光，胶片才感得上光。」', effect: { gold: 80 }, next: 'n5_cab2' },
      n5_cab2: { speaker: 'sys', image: 'item_screen', text: '你拿起一块增感屏，在黑暗里它沉默着。上一代影像科医生的全部骄傲，就锁在这个小柜子里。（回到走廊）', effect: { skill: 1 }, next: 'n5_hub' },

      n5_case0: { bg: 'bg_control', speaker: 'sys', text: '晚上十点，开诊。今晚的急诊格外密——第一位又是吞了异物的孩子。', next: 'n5_case1' },
      n5_case1: { bg: 'bg_xrayroom', speaker: 'father', sprite: 'pat_dad', sfx: 'vox_dad', text: '医生，孩子玩存钱罐，一转眼吞了个东西！我没看清是什么，好像……好像是个圆的！', next: 'n5_case2' },
      n5_case2: { speaker: 'me', text: '圆的。你脑子里立刻跳出第一夜那张片子。但这一次，爸爸没有看清吞的到底是什么——拍片，用图像说话。', sprite: 'pat_dad', next: 'n5_case3' },
      n5_case3: { speaker: 'sys', text: '「嘀——咔！」曝光完成。你抽出IP板，快步送去隔壁扫描仪。', sfx: 'xray', next: 'n5_case3r' },
      n5_case3r: { speaker: 'sys', text: '读取完成。腹部立位片：一个圆形的金属高密度影，端端正正躺在胃里。', readout: 'xray_coin', image: 'xray_coin', next: 'n5_case4' },
      n5_case4: { speaker: 'sys', text: '【仔细看边缘——这一次，它是什么？】', image: 'xray_coin', choices: [
        { text: '纽扣电池！双环征，马上送内镜！', next: 'n5_case5b', effect: { skill: -1, flag: 'n5_wrong' }, tag: 'bad' },
        { text: '一枚硬币——边缘是均匀的一整圈，没有双环', next: 'n5_case5a', effect: { skill: 2 }, tag: 'good' },
      ]},
      n5_case5a: { speaker: 'me', text: '边缘是光滑均匀的一整圈，没有第一夜那种外圈套内圈的双层结构——是硬币。特征征象是用来「看」的，不是用来「背」的：同样圆圆一块，分辨它们靠的是边缘的细节。', next: 'n5_case6' },
      n5_case5b: { speaker: 'zhou', sprite: 'char_zhou', image: 'xray_coin', text: '停！再凑近看——这次边缘是均匀的一整圈，哪来的双环？是硬币。征象是让你核对的，不是让你背的：一见圆形金属影就喊电池，和一见咳嗽就开抗生素，是同一种懒。', next: 'n5_case6' },
      n5_case6: { speaker: 'sys', text: '硬币光滑无腐蚀风险，进入胃部后大多能自行排出——交代观察大便、一周后复查，爸爸千恩万谢地牵着孩子回家了。（这一夜，你忽然意识到自己已经能独立处理这类病例了。）', effect: { gold: 60 }, next: 'n5_gossip0' },
      n5_gossip0: { speaker: 'sys', text: '下一位病人还在路上。小唐抱着保温杯晃过来，一脸「我有料」的表情。', next: 'n5_gossip1' },
      n5_gossip1: { speaker: 'tang', sprite: 'char_tang', text: '白天厂家那个小凯来保养老伙计，一边拧螺丝一边打听「你们夜班谁说了算」。你说他一个修机器的，打听这个干嘛？', next: 'n5_gossip2' },
      n5_gossip2: { speaker: 'tang', text: '那个背皮包的男人今天又来了，还跟老范在楼下抽了根烟。老范回来就把抽屉锁了三道。我瞅见那人名片了——印着「医疗设备循环利用」。啧，说得真好听。', next: 'n5_gossip3' },
      n5_gossip3: { speaker: 'tang', text: '还有两件事：一是听说科主任下周要下科室「随便转转」；二是……老周这个月往医务科跑了三趟了。你说，该不会是咱们科要出什么事吧？', next: 'n5_hot0' },
      n5_hot0: { speaker: 'sys', text: '伤员一个接一个。拍到最后一位时，老伙计的面板突然亮起红灯——「热容量 98%」，蜂鸣器叫了起来。', next: 'n5_hot1' },
      n5_hot1: { speaker: 'tang', sprite: 'char_tang', text: '门外还有最后一个病人等着！怎么办？', next: 'n5_hot2' },
      n5_hot2: { speaker: 'sys', text: '【热容量报警，怎么办？】', sprite: 'char_tang', choices: [
        { text: '跟病人解释，等十分钟让球管冷却再拍', next: 'n5_hot3a', effect: { durability: 5, skill: 1 }, tag: 'good' },
        { text: '就剩最后一个了，硬拍完事', next: 'n5_hot3b', effect: { durability: -15, flag: 'n5_hot' }, tag: 'bad' },
      ]},
      n5_hot3a: { speaker: 'me', text: '电子撞靶，99%的动能变成热量——连续曝光一夜，阳极已经把一整夜的热扛在背上了。这十分钟不是耽误，是让旋转阳极把热散掉。病人听完反而安慰你：「机器也要喘口气嘛，不急。」', next: 'n5_night0' },
      n5_hot3b: { speaker: 'sys', text: '你硬着头皮按下了曝光。图像出来了，但球管里传出一声不对劲的轻响，面板的温度警示过了半小时才退。老周看了看运行日志，什么都没说——这比骂人更让你难受。', next: 'n5_night0' },
      n5_night0: { speaker: 'sys', text: '凌晨三点。科室终于安静下来。你去库房取打印纸，路过检查室时——里面有一线灯光，和刻意压低的说话声。', next: 'n5_night1' },
      n5_night1: { speaker: 'sys', text: '【悄悄看一眼？】', choices: [
        { text: '透过门缝看', next: 'n5_night2', tag: 'good' },
        { text: '不管闲事，回去睡觉', next: 'n5_night2b' },
      ]},
      n5_night2b: { speaker: 'sys', text: '你取了打印纸就回去了。那一线灯光在你身后熄灭了。第二天交班本上干干净净——只是你总觉得，自己错过了什么重要的东西。', next: 'n5_night8' },
      n5_night2: { speaker: 'sys', sprite: 'char_zhou', sprite2: 'pat_oldman', text: '检查室里，老周正扶着一位衣衫单薄的老人躺上检查床，动作轻得像在安放一件瓷器。老人胸廓贴着胶布，咳嗽时整个佝偻的背都在抖。', next: 'n5_night3' },
      n5_night3: { speaker: 'zhou', sprite: 'char_zhou', sprite2: 'pat_oldman', text: '（他回头看见了你，没有惊慌，只是沉默了几秒）……进来吧。把门带上。', next: 'n5_night4' },
      n5_night4: { speaker: 'zhou', sprite: 'char_zhou', sprite2: 'pat_oldman', text: '老爷子睡桥洞，摔了，肋骨怕是断了。没医保，身上八块五。白天门诊他不敢进——挂不起号，也怕人笑话。我这台老伙计，反正闲着也是闲着。', next: 'n5_night5' },
      n5_night5: { speaker: 'sys', text: '【你——】', sprite: 'char_zhou', sprite2: 'pat_oldman', choices: [
        { text: '「我来摆位，您操作——两个人快一点。」（一起拍完）', next: 'n5_night6a', effect: { heart: 2, skill: 1, flag: 'n5_cover' }, tag: 'good', risk: { chance: 0.3, next: 'n5_night6r', effect: { heart: -1 } } },
        { text: '默默退出去，当没看见', next: 'n5_night6b', effect: { heart: 1 }, tag: 'neutral' },
        { text: '「周老师，这不合规矩……被查出来怎么办？」', next: 'n5_night6c', effect: { skill: 1 }, tag: 'neutral' },
      ]},
      n5_night6a: { speaker: 'sys', sprite2: 'pat_oldman', text: '你们一人摆位一人操作，一张胸片，两分钟。左侧第七、八肋骨骨折，还好没有气胸。老周从柜子里拿出自备的胸带，教老人缠好，又写了张纸条：药名、剂量、吃法，字迹一笔一画。', next: 'n5_night7' },
      n5_night6r: { speaker: 'sys', sprite: 'char_zhou', sprite2: 'pat_oldman', text: '（意外）巡夜的护士长路过，看见检查室灯亮着，探头进来：「这么晚还拍片？登记了吗？谁批的？」老周拿出病历夹，平静地答：「急诊加急，我签的字。」护士长走后，他拍拍你肩膀：「好心是好心，下回先跟我报备流程。」（人心-1）', next: 'n5_night6a' },
      n5_night6b: { speaker: 'sys', text: '你轻轻带上了门。第二天交班本上，昨夜的一切干干净净，仿佛什么都没发生。只是垃圾桶里多了一副用过的手套，和一张手写用药说明的草稿。', next: 'n5_night7' },
      n5_night6c: { speaker: 'zhou', sprite: 'char_zhou', text: '（盯着机器看了很久）规矩我懂，我在这台机器前面站了三十年。……可这行最先教我的那句话是：先救人。机器是死的，人是活的。今晚这台机器的钱，从我工资里扣。', next: 'n5_night7' },
      n5_night7: { speaker: 'me', text: '（残影、凌晨三点检查室的灯光、没有登记的片子——全对上了。原来「闹鬼」的片库和机器，藏着的是这样的事。）', effect: { flag: 'zhou_truth' }, next: 'n5_night8' },
      n5_night8: { speaker: 'sys', image: 'item_photo', text: '天蒙蒙亮。你送老人出门，在急诊门口撞见一个熟悉的身影——那个拍过胸片的男人。他正举着一张旧照片，挨个询问早班的人。', next: 'n5_night9' },
      n5_night9: { speaker: 'mystery', sprite: 'pat_mystery', text: '（认出你，迟疑着走近）医生，又见面了。……其实我不是来看病的。我在找人。我父亲，二十年前离家出走前，最后出现的地方就是这家医院。我总梦见他躺在这儿的检查床上……胸口闷，也许就是这么来的。', next: 'n5_night10' },
      n5_night10: { speaker: 'mystery', sprite: 'pat_mystery', text: '他年轻时在这家医院拍过一张片子，我找了好多地方的档案，都没找到。……有时候我想，也许哪间片库里，还存着他的影子。', next: 'n5_night11' },
      n5_night11: { speaker: 'sys', text: '【他的眼神让你心里发沉。怎么回应？】', sprite: 'pat_mystery', choices: [
        { text: '把旧片库和那张1998年无名胶片的事告诉他', next: 'n5_night12a', cond: { flag: 'archive_film' }, effect: { heart: 2, flag: 'mystery_told' }, tag: 'good' },
        { text: '先不声张，等查清那张片子是谁再说', next: 'n5_night12b', cond: { flag: 'archive_sealed' }, tag: 'neutral' },
        { text: '「您留个联系方式，我帮您留意院里的旧档案。」', next: 'n5_night12c', effect: { heart: 1 }, tag: 'good' },
      ]},
      n5_night12c: { speaker: 'sys', text: '你记下了他的联系方式。男人道了谢，走进晨雾里，背影比来时直了一些。……也许哪间片库里，真的还存着他父亲的影子。（这条线，也许下个章节会有回音。）', next: 'n5_night13' },
      n5_night12a: { speaker: 'mystery', sprite: 'pat_mystery', text: '（他的手抖了一下）……真的吗？1998年，对得上，时间对得上！（他深深鞠了一躬）医生，不管那张片子是不是他——谢谢你肯告诉我。这世上肯替陌生人多看一眼的人，不多了。', next: 'n5_night13' },
      n5_night12b: { speaker: 'sys', text: '你只说了一句「我再帮您留意」。男人点点头，走进晨雾里。你摸了摸口袋里的备忘录——「片库深处，封条柜，1999年1月」。谜底，也许就在那里面。', next: 'n5_night13' },
      n5_night13: { speaker: 'zhou', sprite: 'char_zhou', text: '（不知何时站在你身后）下班吧。……今晚看到的，听到的，你心里有数就行。这台机器看人，从来不分有钱没钱。希望你以后也是。', next: 'n5_end0' },
      n5_end0: { speaker: 'sys', text: '【本周夜班 · 结算】诊疗收入 +320 金币。第一章「老伙计」——完。', effect: { gold: 320 }, stamp: true, next: 'n5_end' },
      n5_epi0: { bg: 'bg_morning', speaker: 'sys', text: '考试结束的铃声响起。你交上卷子走出教室，清晨的阳光铺在住院部的走廊上——熬了五个夜班，这一章的考卷，写完了。', next: 'n5_epi1' },
      n5_epi1: { speaker: 'sys', phone: 'char_kai', sfx: 'buzz', text: '手机震了一下。厂家工程师小凯：「考完了？你们那台老伙计，我上周给它做了最后一次深度保养。下个月有台『大家伙』要到咱们县，院长已经看过彩页了。……嘘，别告诉老范是我说的。」', next: 'n5_epi2' },
      n5_epi2: { speaker: 'sys', text: '你正琢磨「大家伙」是什么，走廊尽头响起不紧不慢的脚步声。皮鞋跟敲在水磨石地面上，一下，一下。全科室的人听见这个声音，都会不自觉站直。', next: 'n5_epi3' },
      n5_epi3: { speaker: 'director', sprite: 'char_director', sfx: 'vox_director', text: '（他在你面前站定，目光像CT一样把你从头扫到脚）新来的小同志？……这周的夜班记录，我都看了。干得不错。', next: 'n5_epi4' },
      n5_epi4: { speaker: 'director', sprite: 'char_director', text: '随便问问——上周有一天夜里，检查室的登记本，少了一页。你在值夜班。有印象吗？', next: 'n5_epi5' },
      n5_epi5: { speaker: 'me', text: '（你的心跳漏了一拍。凌晨三点的灯光、桥洞边的老人、老周轻得像羽毛的动作……你张了张嘴，喉咙发干。）', next: 'n5_epi6' },
      n5_epi6: { speaker: 'director', sprite: 'char_director', text: '（他看了你两秒，忽然笑了笑，笑意没到眼睛）例行问问，别紧张。……对了，CT的批文，昨天下来了。明年这个时候，你们影像科，要变天了。', next: 'n5_epi7' },
      n5_epi7: { speaker: 'sys', text: '他转身离开，皮鞋声一下一下远了。你靠着墙站了一会儿，才发现手心全是汗。', next: 'n5_epi8' },
      n5_epi8: { speaker: 'sys', phone: 'char_he', sfx: 'buzz', text: '手机又震了。急诊科小何的语音留言，背景里全是平车轮子的声音：「周末科室聚餐！老周说他要宣布个事，点名你必须到……欸你说，他该不会是要退休了吧？！」', next: 'n5_epi9' },
      n5_epi9: { speaker: 'me', text: '（宣布个事？登记本少掉的那一页，主任为什么偏偏问你？老周往医务科跑的那些下午……你忽然觉得，这五个夜晚看懂的东西，只是这间科室的冰山一角。）', next: 'n5_epi10' },
      n5_epi10: { speaker: 'sys', image: 'img_teaser', text: '第一章 ·「老伙计」—— 完。', next: 'n5_epi11' },
      n5_epi11: { speaker: 'sys', image: 'img_teaser', text: '第二章「快与狠」· CT篇 —— 黑了大半年的CT室，等来了它的新主人。而有些人，要在新机器进场之前，先学会告别。敬请期待。', next: 'n5_epi_end' },
      n5_epi_end: { end: true },
      n5_end: { end: true },
    },
  },
]

/* ================= 晨会考核（第5夜后 · 20题题库随机抽5） ================= */
export interface QuizQuestion { q: string; options: string[]; answer: number; explain: string }
export const QUIZ: QuizQuestion[] = [
  { q: 'X射线的本质是？',
    options: ['高速电子流', '一种波长较短的电磁波（约0.001~10nm）', '超声波的一种', '放射性同位素释放的α粒子'],
    answer: 1,
    explain: 'X射线是电磁波，1895年伦琴发现，医学诊断用波长约0.01~0.1nm。它走直线、不带电、不受电磁场偏折——正因"未知"才被命名为X。' },
  { q: '医用X射线的主要产生方式是？（课件原题）',
    options: ['高频声波震动', '化学反应', '高速电子撞击金属靶材', '光电效应'],
    answer: 2,
    explain: '四要素：电子源、合适的靶、强电场、真空环境。强电场加速电子，高速电子与靶原子撞击产生X射线。' },
  { q: '高速电子撞击钨靶时，动能大约有多少转化为X射线？',
    options: ['约50%', '约99%', '约10%', '约1%'],
    answer: 3,
    explain: '只有约1%是辐射损失（X射线），约99%是碰撞损失变成热——阳极常用钨、钼这类高原子序数且高熔点的材料，就是为了扛住这份热。' },
  { q: '轫致辐射（刹车辐射）和标识辐射（特征辐射）的主要区别是？（课件原题）',
    options: ['刹车辐射产生于阳极，特征辐射产生于阴极', '刹车辐射是连续谱，特征辐射是线谱', '特征辐射的能量一定比刹车辐射高', '刹车辐射仅在高电压下产生，特征辐射不受电压影响'],
    answer: 1,
    explain: '刹车辐射是电子在靶原子核电场中减速释放的连续谱；特征辐射是内层电子跃迁填补空穴放出的特征谱线，医学应用一般只用K系。' },
  { q: '轫致辐射能产生X射线的最短波长，取决于什么？',
    options: ['管电压（入射电子的能量）', '灯丝电流', '靶的厚度', '曝光时间'],
    answer: 0,
    explain: '最短波长对应单个电子的全部能量：λmin = hc/eV。管电压越高，最短波长越小、射线越"硬"。' },
  { q: 'X射线管中，X射线实际产生于？（课件原题）',
    options: ['阴极', '栅格', '准直器', '阳极'],
    answer: 3,
    explain: '阴极灯丝只负责发射电子；电子高速轰击阳极金属靶（钨/钼/铑，高Z高熔点），在靶面上产生X射线。' },
  { q: '关于X射线管管电流的影响因素，正确的说法是？',
    options: ['只由灯丝电流决定，与管电压无关', '只由管电压决定，与灯丝电流无关', '管电压较低时管电流受空间电荷限制；管电压足够高时趋于饱和，饱和值由灯丝电流（灯丝温度）决定', '与灯丝温度无关'],
    answer: 2,
    explain: '灯丝电流烧热灯丝，决定发射的电子数；但管电压低时，堆积在灯丝周围的电子云（空间电荷）会把部分电子挡回去，管电流达不到饱和。管电压足够高、电子被全数拉走后，管电流才由灯丝温度说了算。所以想加大管电流：灯丝要烧热，管电压也要给够。' },
  { q: '球管焦点的大小对成像有何影响？（课件原题）',
    options: ['焦点越大，成像速度越慢', '焦点越小，成像的细节分辨率越高', '焦点大小不影响成像质量', '焦点越大，图像对比度越高'],
    answer: 1,
    explain: '有效焦点直接影响成像分辨率：越小越清晰；但小焦点热容量低，扛不住大剂量长时间曝光——这就是双焦点设计存在的原因。' },
  { q: '球管热容量（HU）的计算方式是？',
    options: ['管电压 × 管电流 × 时间', '管电压 ÷ 管电流', '管电流 × 焦点面积', '管电压 × 曝光次数'],
    answer: 0,
    explain: 'HU = kVp × mA × s。普通X射线设备球管热容量几百KHU，CT球管高达2~10MHU——这就是夜班连拍要让老伙计"歇口气"的原因。' },
  { q: '在医用X射线成像中，光电效应的主要贡献是？（课件原题）',
    options: ['产生散射辐射，降低图像质量', '增加X射线的穿透力', '增加对X射线的吸收，提升对比度', '生成更多热量，限制X射线产生'],
    answer: 2,
    explain: '光电效应截面∝Z⁴/hν³，原子序数差异被急剧放大，组织对比度高、还不产生灰雾。低能X射线与高原子序数物质作用时它占优势。' },
  { q: '康普顿散射对X射线图像的影响是？',
    options: ['提高图像对比度', '让图像整体蒙上一层灰雾，降低对比度', '使图像边缘更锐利', '完全没有影响'],
    answer: 1,
    explain: '入射光子部分能量传给电子、方向改变，散射光子均匀分布在整个空间，叠成灰雾。床旁片发灰、影像对比度下降，元凶就是它。' },
  { q: '单能窄束X射线穿过均匀物质时的衰减规律是？',
    options: ['线性递减：I = I0 − μx', '指数衰减：I = I0·e^(−μx)', '与距离平方成反比', '完全不衰减'],
    answer: 1,
    explain: 'I = I0·e^(−μx)，μ是线性衰减系数，与光子能量、物质原子序数和密度有关。半值层HVL = 0.693/μ。' },
  { q: 'X射线机加装滤过板（以铝当量mmAl表示）的主要目的是？',
    options: ['让图像更好看', '滤掉低能软射线，减少病人剂量并抑制束线硬化', '提高管电流', '防止机器被盗'],
    answer: 1,
    explain: '低能光子穿不透人体、只会白吃剂量还造成束线硬化伪影。固有滤过加附加滤过提前把射线"变硬"，是最基本的低剂量手段之一。' },
  { q: 'X射线增感屏基于的效应是？（课件原题）',
    options: ['康普顿效应', '荧光效应', '穿透效应', '反射效应'],
    answer: 1,
    explain: '增感屏（钨酸钙、稀土硫氧化钆等）把X射线转成可见荧光再让胶片感光——单独用胶片只吸收约1%的X射线，增感屏大幅降低曝光量和剂量。' },
  { q: 'CR（计算机X射线摄影）的核心成像环节是？',
    options: ['胶片直接感光后显影定影', 'IP成像板存储潜影，再经激光扫描二次发光读出（PSL）', '探测器直接把X射线转成电信号', '用摄像头翻拍荧光屏'],
    answer: 1,
    explain: 'CR用含光激励发光材料的IP板（氟卤化钡掺铕）采集潜影，激光扫描读出。IP板可重复使用、动态范围大，但时间分辨力差、还得抱着板子跑扫描仪。' },
  { q: 'DR和CR成像技术的主要区别是？（课件原题）',
    options: ['DR使用X射线，CR不使用', 'CR图像质量优于DR', 'DR探测器直接把X射线转成数字信号，CR需要IP板读出', 'DR必须使用对比剂，CR不需要'],
    answer: 2,
    explain: 'DR转换环节少、图像质量高、拍完秒出图，是目前医院主流；CR要搬运IP板去扫描，效率低一截。' },
  { q: '关于平板探测器（FPD）的选型，正确的是？',
    options: ['非晶硅（间接型）空间分辨率最高，适合乳腺', '非晶硒（直接型）不产生可见光散射，空间分辨率高，适合乳腺、四肢关节等细节成像', '两种探测器原理完全相同', 'CCD摄像机型是目前绝对主流'],
    answer: 1,
    explain: '非晶硒直接型没有可见光散射，分辨率取决于TFT矩阵，适合看细节；非晶硅间接型经碘化铯闪烁体转换，DQE高、密度分辨力强，适合胸部这类看密度差异的检查。' },
  { q: 'DSA（数字减影血管造影）主要用于？（课件原题）',
    options: ['骨折诊断', '肺部疾病诊断', '脑部结构成像', '血管病变的检测和评估'],
    answer: 3,
    explain: 'DSA用造影前后的充盈像减去掩模像，消除骨骼软组织背景，让低浓度对比剂的血管清晰显示。冠脉造影经桡动脉/股动脉送心导管，就是它的经典应用。' },
  { q: '乳腺钼靶成像选择钼做靶材的原因是？（课件原题）',
    options: ['钼靶能产生高能X射线，穿透更厚组织', '钼靶的Kα（17.5keV）、Kβ（19.6keV）特征辐射能量适中，利于软组织间光电效应对比', '钼靶能减少散射，避免图像模糊', '钼最便宜'],
    answer: 1,
    explain: '低管电压（一般40kV以下）下光电效应占优，而光电效应对Z差异极敏感——脂肪、腺体这些软组织对比度被拉开。20keV以上部分会被滤掉以平衡剂量。' },
  { q: '关于辐射剂量与防护的单位和概念，正确的是？',
    options: ['吸收剂量单位是戈瑞（Gy），当量剂量单位是希伏（Sv），屏蔽材料用铅当量（mmPb）衡量', '剂量越大图像一定越好，无需控制', 'X射线不是电离辐射，对人体无害', '防护只要距离远，屏蔽没用'],
    answer: 0,
    explain: 'Gy=1J/kg吸收能量；Sv在Gy基础上乘以射线类型系数。X射线是电离辐射，防护三原则：时间、距离、屏蔽（铅衣、铅玻璃，以mmPb计）。' },
]

/* ================= 值班室旧书:《医学影像学》残页(每夜解锁一页,内容为考题/剧情未覆盖的补充知识) ================= */
export const BOOK_PAGES: { title: string; body: string; note: string }[] = [
  {
    title: '球管里发生了什么:灯丝、聚焦罩与旋转阳极',
    body: '阴极灯丝通电烧到两千多度,把电子「蒸发」出来——这叫热电子发射,灯丝电流决定了有多少电子可用。灯丝外面罩着一只带凹槽的聚焦罩,它带着负电,把发散的电子流捏成细细的一束,对准阳极靶面上小小的一点。\n阳极其实是一只高速旋转的合金圆盘:电子束打在盘沿的钨靶面上,圆盘每转一圈,受热的位置就换一拨——热量被摊到整个盘沿,而不是烧穿同一个点。靶面还做成倾斜的:斜面把「实际焦点」摊开散热,而投向病人的「有效焦点」依然很小,图像才够锐利。',
    note: '页边一行褪色的钢笔字:「焦点越小越清楚,但越小越烫——鱼与熊掌。」',
  },
  {
    title: '能谱长什么样:山丘上戳着几根针',
    body: '把X光按能量画成一张分布图:刹车辐射画出来是一座平缓的山丘,从很低一路铺到管电压对应的最高能量;特征辐射则是山丘上笔直戳出来的几根针。\n针的位置只由靶材决定:钨的Kα线在 59.3 keV——那是 L 层电子跌进 K 层空位时交出来的能量;M 层跌进来的是 Kβ,能量更高一点、也更稀疏。要是管电压不到 69.5 kV,电子连钨的 K 层电子都轰不出去,这几根针就根本不会出现在谱里。\n所以换靶材、调电压,本质上是在挪动这座山丘和那几根针。',
    note: '页边小字:「软组织的戏,全在山丘的左半边。」',
  },
  {
    title: '光电效应:一次干净的吸收',
    body: '能量合适的光子撞上原子的内层电子,会把自己整个交出去——光子消失,电子获得能量飞走,这叫光电效应。没有散射、没有拖泥带水的二次光子,是一次「干净」的吸收。\n它对原子序数敏感得近乎苛刻:吸收本领约与 Z 的四次方成正比。骨骼里的钙(Z=20)因此比肌肉(等效 Z≈7.4)吸得凶得多,片子上就白得多。\n钡餐和碘造影剂也是同一个道理——用高原子序数的物质,人为把脏器的轮廓「涂」出来。',
    note: '页边小字:「拍片先想 Z。Z 差就是对比度的本钱。」',
  },
  {
    title: '康普顿散射:撞歪的那部分光子',
    body: '能量较高的光子与原子的外层电子相撞,像台球杆擦着球边:光子把一部分能量交给电子(它被称为反冲电子),自己带着剩下的能量、换个方向继续飞——能量变低,波长变长。\n这些散射光子朝四面八方乱飞,有一部分甚至会掉头折返。所以机房里需要防护的从来不只是直射的那一束:病人体内散出来的散射,才是摆位时技师和陪床家属吃剂量的主要来源——铅围裙防的主要是它。',
    note: '页边小字:「别站在病人和球管之间,也别站在散射的路上。」',
  },
  {
    title: '滤线栅:一把铅条梳子',
    body: '把几十根薄铅条按球管焦点的方向排成一把「梳子」,立在病人和探测器之间:直进的有用光子顺着缝隙穿过去,斜着杀来的散射光子大半被铅条吃掉——这就是滤线栅。\n铅条高度与间距之比叫栅比:栅比越大滤得越狠,但曝光量也得跟着加。会聚栅的铅条是对准焦点斜着排的,装反了、或者球管没对准中心,图像边缘会被无辜削掉一片——行话叫「栅切割」。',
    note: '这一页被翻得最烂。页边小字:「床旁机没这把梳子,所以床旁片总是灰蒙蒙的。」',
  },
]
